/**
 * Geo constants for checkout: countries, Nigerian states, Lagos LGAs.
 * Mirrors the seed data in scripts/seed-logistics-rates.js.
 */

export interface GeoOption {
  name: string;
  code: string;
}

// ── 195 world countries (Nigeria first, then alphabetical) ─────────
export const WORLD_COUNTRIES: GeoOption[] = [
  { name: "Nigeria", code: "NG" },
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Brazil", code: "BR" },
  { name: "Brunei", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cabo Verde", code: "CV" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo (Brazzaville)", code: "CG" },
  { name: "Congo (DRC)", code: "CD" },
  { name: "Costa Rica", code: "CR" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "East Timor", code: "TL" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Eswatini", code: "SZ" },
  { name: "Ethiopia", code: "ET" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR" },
  { name: "Grenada", code: "GD" },
  { name: "Guatemala", code: "GT" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Honduras", code: "HN" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Ivory Coast", code: "CI" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Kosovo", code: "XK" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia", code: "FM" },
  { name: "Moldova", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "North Korea", code: "KP" },
  { name: "North Macedonia", code: "MK" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestine", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Qatar", code: "QA" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Korea", code: "KR" },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syria", code: "SY" },
  { name: "Taiwan", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Togo", code: "TG" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Vatican City", code: "VA" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

// ── 37 Nigerian states + FCT ──────────────────────────────────────
export const NIGERIAN_STATES: GeoOption[] = [
  { name: "Abia", code: "NG-AB" },
  { name: "Adamawa", code: "NG-AD" },
  { name: "Akwa Ibom", code: "NG-AK" },
  { name: "Anambra", code: "NG-AN" },
  { name: "Bauchi", code: "NG-BA" },
  { name: "Bayelsa", code: "NG-BY" },
  { name: "Benue", code: "NG-BE" },
  { name: "Borno", code: "NG-BO" },
  { name: "Cross River", code: "NG-CR" },
  { name: "Delta", code: "NG-DE" },
  { name: "Ebonyi", code: "NG-EB" },
  { name: "Edo", code: "NG-ED" },
  { name: "Ekiti", code: "NG-EK" },
  { name: "Enugu", code: "NG-EN" },
  { name: "Abuja (FCT)", code: "NG-FC" },
  { name: "Gombe", code: "NG-GO" },
  { name: "Imo", code: "NG-IM" },
  { name: "Jigawa", code: "NG-JI" },
  { name: "Kaduna", code: "NG-KD" },
  { name: "Kano", code: "NG-KN" },
  { name: "Katsina", code: "NG-KT" },
  { name: "Kebbi", code: "NG-KE" },
  { name: "Kogi", code: "NG-KO" },
  { name: "Kwara", code: "NG-KW" },
  { name: "Lagos", code: "NG-LA" },
  { name: "Nasarawa", code: "NG-NA" },
  { name: "Niger", code: "NG-NI" },
  { name: "Ogun", code: "NG-OG" },
  { name: "Ondo", code: "NG-ON" },
  { name: "Osun", code: "NG-OS" },
  { name: "Oyo", code: "NG-OY" },
  { name: "Plateau", code: "NG-PL" },
  { name: "Rivers", code: "NG-RI" },
  { name: "Sokoto", code: "NG-SO" },
  { name: "Taraba", code: "NG-TA" },
  { name: "Yobe", code: "NG-YO" },
  { name: "Zamfara", code: "NG-ZA" },
];

// ── 20 Lagos LGAs ─────────────────────────────────────────────────
export const LAGOS_LGAS: GeoOption[] = [
  { name: "Agege", code: "NG-LA-AGEGE" },
  { name: "Ajeromi-Ifelodun", code: "NG-LA-AJEROMI" },
  { name: "Alimosho", code: "NG-LA-ALIMOSHO" },
  { name: "Amuwo-Odofin", code: "NG-LA-AMUWO" },
  { name: "Apapa", code: "NG-LA-APAPA" },
  { name: "Badagry", code: "NG-LA-BADAGRY" },
  { name: "Epe", code: "NG-LA-EPE" },
  { name: "Eti-Osa (Lekki / VI / Ikoyi)", code: "NG-LA-ETI-OSA" },
  { name: "Ibeju-Lekki", code: "NG-LA-IBEJU" },
  { name: "Ifako-Ijaiye", code: "NG-LA-IFAKO" },
  { name: "Ikeja", code: "NG-LA-IKEJA" },
  { name: "Ikorodu", code: "NG-LA-IKORODU" },
  { name: "Kosofe", code: "NG-LA-KOSOFE" },
  { name: "Lagos Island", code: "NG-LA-ISLAND" },
  { name: "Lagos Mainland", code: "NG-LA-MAINLAND" },
  { name: "Mushin", code: "NG-LA-MUSHIN" },
  { name: "Ojo", code: "NG-LA-OJO" },
  { name: "Oshodi-Isolo", code: "NG-LA-OSHODI" },
  { name: "Somolu", code: "NG-LA-SOMOLU" },
  { name: "Surulere", code: "NG-LA-SURULERE" },
];
