-- ============================================================
-- MIGRATION 000101 — Shared E-Signature Workflow (V2.2 §6.13 + §6.26)
-- Pixie Girl Hub · JBS Praxis · Conformance pass V2.2
--
-- B-10: Full e-signature workflow tables (per user decision).
--
-- The flow:
--   1. Document is uploaded / generated and stored in shared.documents
--   2. Someone (HR, CEO, contract manager) opens a signature_request
--   3. One or more signers are added (sequential or parallel)
--   4. Each signer gets a unique signing URL (token-based, no login required
--      for external parties; logged-in users sign in-app)
--   5. Signer reviews → signs (captures image of signature + IP + device)
--   6. Audit events log every interaction
--   7. When all signers sign, document is "fully signed" — frozen via
--      trigger on shared.documents (no further edits allowed)
--   8. Final signed PDF generated by the app and replaces the document file
--
-- Tables:
--   signature_requests          — the request itself
--   signature_request_signers   — one row per required signer
--   signature_audit_events      — tamper-evident audit trail
--
-- Schema changes:
--   shared.documents: add signing_state + frozen_at columns
--   shared.documents: trigger blocks UPDATE/DELETE when frozen_at IS NOT NULL
--                     (except by service role; bypasses for storage_path
--                     update when the signed PDF is generated)
-- ============================================================

-- ╔════════════════════════════════════════════════════════════════════╗
-- ║ SIGNATURE_REQUESTS                                                 ║
-- ╚════════════════════════════════════════════════════════════════════╝

CREATE TABLE shared.signature_requests (
  request_id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  business              TEXT        NOT NULL REFERENCES shared.business_config (business_key) ON DELETE RESTRICT,
  -- The document being signed
  document_id           UUID        NOT NULL REFERENCES shared.documents (document_id) ON DELETE RESTRICT,
  -- What kind of agreement is this? Drives template + required signer count.
  request_type          TEXT        NOT NULL
                        CHECK (request_type IN (
                          'stylist_partner_agreement',  -- V2.2 §6.26
                          'employment_contract',
                          'nda',
                          'supplier_agreement',
                          'service_agreement',
                          'investor_document',
                          'other'
                        )),
  -- Reference to the source object (the stylist row, employee row, etc.)
  -- Soft FK — varies by request_type, resolved in app
  reference_type        TEXT,
  reference_id          UUID,
  -- Signing order
  signing_order         TEXT        NOT NULL DEFAULT 'sequential'
                        CHECK (signing_order IN ('sequential','parallel')),
  -- Lifecycle
  status                TEXT        NOT NULL DEFAULT 'draft'
                        CHECK (status IN (
                          'draft',                 -- being prepared
                          'sent',                  -- emails out, signers awaiting
                          'partially_signed',      -- at least one but not all signed
                          'fully_signed',          -- all done
                          'declined',              -- a required signer declined
                          'expired',               -- past expires_at
                          'cancelled',             -- creator pulled it
                          'voided'                 -- post-signing, voided by CEO
                        )),
  -- Subject / message shown to signers
  subject               TEXT        NOT NULL,
  message               TEXT,
  -- Expiry
  expires_at            TIMESTAMPTZ,
  -- Final signed artifact
  signed_document_id    UUID        REFERENCES shared.documents (document_id) ON DELETE SET NULL,
  fully_signed_at       TIMESTAMPTZ,
  -- Audit
  created_by            UUID        REFERENCES shared.users (user_id) ON DELETE SET NULL,
  sent_at               TIMESTAMPTZ,
  cancelled_at          TIMESTAMPTZ,
  cancelled_by          UUID        REFERENCES shared.users (user_id) ON DELETE SET NULL,
  voided_at             TIMESTAMPTZ,
  voided_by             UUID        REFERENCES shared.users (user_id) ON DELETE SET NULL,
  void_reason           TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_signature_requests_updated_at
  BEFORE UPDATE ON shared.signature_requests
  FOR EACH ROW EXECUTE FUNCTION shared.fn_set_updated_at();
CREATE INDEX idx_signature_requests_business_status
  ON shared.signature_requests (business, status, created_at DESC);
CREATE INDEX idx_signature_requests_document
  ON shared.signature_requests (document_id);
CREATE INDEX idx_signature_requests_pending
  ON shared.signature_requests (business, expires_at)
  WHERE status IN ('sent','partially_signed');
CREATE INDEX idx_signature_requests_reference
  ON shared.signature_requests (reference_type, reference_id)
  WHERE reference_id IS NOT NULL;

-- ╔════════════════════════════════════════════════════════════════════╗
-- ║ SIGNATURE_REQUEST_SIGNERS                                          ║
-- ╚════════════════════════════════════════════════════════════════════╝

CREATE TABLE shared.signature_request_signers (
  signer_id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id            UUID        NOT NULL REFERENCES shared.signature_requests (request_id) ON DELETE CASCADE,
  -- The signer's identity — exactly one of these three resolves
  user_id               UUID        REFERENCES shared.users (user_id) ON DELETE RESTRICT,
  contact_id            UUID        REFERENCES shared.contacts (contact_id) ON DELETE RESTRICT,
  -- For external parties with no record on file
  external_name         TEXT,
  external_email        CITEXT,
  external_phone        TEXT,
  -- Display info (snapshot — for the audit if records later change)
  display_name_snapshot TEXT        NOT NULL,
  display_email_snapshot CITEXT     NOT NULL,
  -- Role / capacity in which they sign
  signer_role           TEXT        NOT NULL,                   -- 'Stylist','Employee','CEO','Witness','Counterparty'
  -- Order (for sequential signing); 1 = first
  signing_step          SMALLINT    NOT NULL,
  -- Unique signing token (gives them access to the signing page without login)
  signing_token         TEXT        NOT NULL UNIQUE,
  signing_token_expires_at TIMESTAMPTZ,
  -- Lifecycle
  status                TEXT        NOT NULL DEFAULT 'pending'
                        CHECK (status IN (
                          'pending',     -- email not yet sent (sequential, before their turn)
                          'sent',        -- email delivered, awaiting them
                          'viewed',      -- they opened the signing link
                          'signed',      -- done
                          'declined',
                          'expired',
                          'voided'
                        )),
  -- Captured signature artifact
  captured_signature_path TEXT,                                 -- relative path inside media storage
  signature_image_byte_size INTEGER,
  -- Capture context
  signed_at             TIMESTAMPTZ,
  signed_ip             INET,
  signed_user_agent     TEXT,
  signed_device         TEXT,
  -- Audit hash — SHA256 of (signed_at|signer_id|document_id|signature_path) at sign time
  audit_hash            TEXT,
  -- Decline tracking
  declined_at           TIMESTAMPTZ,
  decline_reason        TEXT,
  -- Reminder cadence
  last_reminder_sent_at TIMESTAMPTZ,
  reminder_count        SMALLINT    NOT NULL DEFAULT 0,
  -- Audit
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Constraints
  CONSTRAINT signer_identity_exactly_one
    CHECK (
      (user_id IS NOT NULL)::int +
      (contact_id IS NOT NULL)::int +
      ((external_name IS NOT NULL AND external_email IS NOT NULL))::int = 1
    ),
  CONSTRAINT signer_signed_consistency
    CHECK (
      status <> 'signed' OR (
        signed_at IS NOT NULL
        AND captured_signature_path IS NOT NULL
        AND audit_hash IS NOT NULL
      )
    ),
  UNIQUE (request_id, signing_step)
);
CREATE TRIGGER trg_signature_request_signers_updated_at
  BEFORE UPDATE ON shared.signature_request_signers
  FOR EACH ROW EXECUTE FUNCTION shared.fn_set_updated_at();
CREATE INDEX idx_signature_signers_request
  ON shared.signature_request_signers (request_id, signing_step);
CREATE INDEX idx_signature_signers_pending
  ON shared.signature_request_signers (status, signing_token_expires_at)
  WHERE status IN ('sent','viewed');
CREATE INDEX idx_signature_signers_user
  ON shared.signature_request_signers (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX idx_signature_signers_contact
  ON shared.signature_request_signers (contact_id) WHERE contact_id IS NOT NULL;

-- ╔════════════════════════════════════════════════════════════════════╗
-- ║ SIGNATURE_AUDIT_EVENTS                                             ║
-- ║ Tamper-evident event log. Every action against a signature request║
-- ║ gets a row here. Append-only — UPDATE/DELETE blocked.              ║
-- ╚════════════════════════════════════════════════════════════════════╝

CREATE TABLE shared.signature_audit_events (
  event_id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id            UUID        NOT NULL REFERENCES shared.signature_requests (request_id) ON DELETE CASCADE,
  signer_id             UUID        REFERENCES shared.signature_request_signers (signer_id) ON DELETE CASCADE,
  -- Event type
  event_type            TEXT        NOT NULL
                        CHECK (event_type IN (
                          'request_created',
                          'request_sent',
                          'reminder_sent',
                          'email_delivered',
                          'email_bounced',
                          'signing_link_opened',
                          'document_viewed',
                          'document_downloaded',
                          'signed',
                          'declined',
                          'cancelled',
                          'expired',
                          'voided',
                          'fully_signed',
                          'tamper_check_pass',
                          'tamper_check_fail'
                        )),
  -- Tech context
  ip_address            INET,
  user_agent            TEXT,
  device                TEXT,
  geo_country_code      CHAR(2),
  -- Free-form payload
  metadata              JSONB,
  -- Hash chain — each event's hash includes the previous event's hash,
  -- forming an immutable chain (Bitcoin-style). Tamper attempts on the
  -- audit log break the chain.
  prev_event_hash       TEXT,
  event_hash            TEXT        NOT NULL,
  -- Timing
  occurred_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_signature_audit_request
  ON shared.signature_audit_events (request_id, occurred_at);
CREATE INDEX idx_signature_audit_signer
  ON shared.signature_audit_events (signer_id, occurred_at)
  WHERE signer_id IS NOT NULL;
CREATE INDEX idx_signature_audit_event_type_day
  ON shared.signature_audit_events (event_type, occurred_at);

-- Block updates/deletes on audit events (tamper-evident)
CREATE OR REPLACE FUNCTION shared.fn_signature_audit_append_only()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'signature_audit_events is append-only — tamper-evident chain (V2.2 §6.13 e-signature)';
END;
$$;

CREATE TRIGGER trg_signature_audit_no_update
  BEFORE UPDATE OR DELETE ON shared.signature_audit_events
  FOR EACH ROW EXECUTE FUNCTION shared.fn_signature_audit_append_only();

-- ╔════════════════════════════════════════════════════════════════════╗
-- ║ shared.documents: signing_state + frozen_at                        ║
-- ║                                                                    ║
-- ║ NOTE: documents already has trg_documents_immutable (from 000013)  ║
-- ║ blocking edits to file_path/content_hash. The frozen lock adds     ║
-- ║ a second layer: once a document is fully_signed, even the         ║
-- ║ soft-delete fields cannot change.                                  ║
-- ╚════════════════════════════════════════════════════════════════════╝

ALTER TABLE shared.documents
  ADD COLUMN signing_state TEXT NOT NULL DEFAULT 'none'
    CHECK (signing_state IN ('none','signing_in_progress','partially_signed','fully_signed','voided'));

ALTER TABLE shared.documents
  ADD COLUMN frozen_at TIMESTAMPTZ;

COMMENT ON COLUMN shared.documents.signing_state IS
  'B-10: tracks any active signature_request against this document. Set by app code.';
COMMENT ON COLUMN shared.documents.frozen_at IS
  'B-10: set when document becomes fully_signed. Soft-delete blocked while frozen.';

-- Block deletion of frozen documents (the existing immutable trigger handles
-- updates to file_path; this guard prevents even is_deleted=true on a signed doc)
CREATE OR REPLACE FUNCTION shared.fn_documents_frozen_lock()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.frozen_at IS NOT NULL THEN
    -- Block soft delete + delete on frozen docs
    IF TG_OP = 'DELETE' THEN
      RAISE EXCEPTION
        'Document % is frozen (signed at %): cannot be deleted',
        OLD.document_id, OLD.frozen_at;
    END IF;
    -- UPDATE: block flipping is_deleted to true on a frozen doc
    IF TG_OP = 'UPDATE' AND NEW.is_deleted = true AND OLD.is_deleted = false THEN
      RAISE EXCEPTION
        'Document % is frozen (signed at %): cannot be soft-deleted',
        OLD.document_id, OLD.frozen_at;
    END IF;
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_documents_frozen_lock
  BEFORE UPDATE OR DELETE ON shared.documents
  FOR EACH ROW EXECUTE FUNCTION shared.fn_documents_frozen_lock();

-- ============================================================
-- After this migration: shared schema gains 3 new tables
--   • signature_requests
--   • signature_request_signers
--   • signature_audit_events
-- Plus documents.signing_state + frozen_at + lock trigger
-- ============================================================
