-- Migration 000215: Factory i18n — shared language registry for the factory
-- portal UI (ledger, shipments). Stores per-language translation bundles as
-- JSONB so the frontend can boot in any supported locale.

CREATE TABLE IF NOT EXISTS shared.factory_i18n (
  language_code  TEXT PRIMARY KEY,
  display_name   TEXT NOT NULL,
  translations   JSONB NOT NULL DEFAULT '{}',
  is_active      BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed English (always required as base language)
INSERT INTO shared.factory_i18n (language_code, display_name, translations) VALUES
('en', 'English', '{"currentBalance":"Current Balance","alertThreshold":"Alert threshold","reconcile":"Reconcile ({{count}})","addEntry":"Add Entry","balanceExceeded":"Balance has exceeded the alert threshold. Please arrange payment.","date":"Date","type":"Type","description":"Description","debit":"Debit","credit":"Credit","balance":"Balance","reconCol":"Recon.","noEntries":"No ledger entries yet","noEntriesMsg":"Order charges and payments will appear here.","failedToLoad":"Failed to load","couldNotLoadEntries":"Could not load ledger entries.","couldNotLoadShipments":"Could not load shipments.","retry":"Retry","addLedgerEntry":"Add Ledger Entry","cancel":"Cancel","saving":"Saving…","saveEntry":"Save Entry","entryType":"Entry Type","amount":"Amount","currency":"Currency","fxRate":"FX Rate to CNY","paymentMethod":"Payment Method","selectPrompt":"— Select —","paidBy":"Paid By","paidByPlaceholder":"Person / entity name","descriptionPlaceholder":"Short description (optional)","all":"All","newShipment":"New Shipment","noShipments":"No shipments yet","noShipmentsMsg":"When the factory dispatches goods, log the shipment here.","items":"items","shipped":"Shipped","estimatedArrival":"Est. arrival","courier":"Courier","tracking":"Tracking","shippingFee":"Shipping Fee","itemsLabel":"Items","advanceStatus":"Advance Status","advanceTo":"Advance to","updating":"Updating…","confirm":"Confirm","createShipment":"Create Shipment","courierPlaceholder":"e.g. DHL, FedEx, Yanwen","trackingNumber":"Tracking Number","trackingPlaceholder":"Optional","shippedDate":"Shipped Date","unitPrice":"Unit Price ¥","qty":"Qty","add":"Add","noFactoryAccounts":"No factory accounts","noFactoryAccountsMsg":"No factory accounts have been set up yet.","ledger":"Ledger","shipmentsTab":"Shipments","shipment":"Shipment","langToggle":"EN"}'::jsonb),
('zh', '简体中文', '{"currentBalance":"当前余额","alertThreshold":"预警阈值","reconcile":"对账 ({{count}})","addEntry":"添加记录","balanceExceeded":"余额已超过预警阈值，请及时付款。","date":"日期","type":"类型","description":"描述","debit":"借方","credit":"贷方","balance":"余额","reconCol":"对账","noEntries":"暂无记录","noEntriesMsg":"订单收费和付款将显示在这里。","failedToLoad":"加载失败","couldNotLoadEntries":"无法加载账户记录。","couldNotLoadShipments":"无法加载发货记录。","retry":"重试","addLedgerEntry":"添加账户记录","cancel":"取消","saving":"保存中…","saveEntry":"保存","entryType":"类型","amount":"金额","currency":"货币","fxRate":"汇率（转换为CNY）","paymentMethod":"付款方式","selectPrompt":"— 选择 —","paidBy":"付款人","paidByPlaceholder":"付款人姓名","descriptionPlaceholder":"备注（选填）","all":"全部","newShipment":"新建发货单","noShipments":"暂无发货记录","noShipmentsMsg":"工厂发货后，记录在这里。","items":"件","shipped":"发货","estimatedArrival":"预计到达","courier":"快递公司","tracking":"追踪号","shippingFee":"运费","itemsLabel":"货物明细","advanceStatus":"更新状态","advanceTo":"更新为","updating":"更新中…","confirm":"确认","createShipment":"创建发货单","courierPlaceholder":"如：DHL、FedEx","trackingNumber":"追踪号","trackingPlaceholder":"追踪号（选填）","shippedDate":"发货日期","unitPrice":"单价(CNY)","qty":"数量","add":"添加","noFactoryAccounts":"暂无工厂账户","noFactoryAccountsMsg":"尚未设置工厂账户。","ledger":"账户记录","shipmentsTab":"发货记录","shipment":"发货单","langToggle":"中文"}'::jsonb)
ON CONFLICT (language_code) DO NOTHING;
