-- ============================================================
-- MIGRATION 000231 — Premium, brand-aware email templates
-- Pixie Girl Hub · JBS Praxis · V2.2
--
-- GENERATED by scripts/gen-premium-email-templates.js from the single skin in
-- src/services/email-theme.js. Do not hand-edit — re-run the generator.
--
-- Replaces the bare seeded templates (`<h1>Welcome!</h1>`) with one luxury,
-- table-based, inline-CSS, Outlook/Gmail/Apple-safe skin. All brand identity
-- (logo, accent colour, name, links, address) is left as {{tokens}} that the
-- send pipeline (email-render.js) fills per brand from Settings, so the same
-- template reskins itself for Pixie Girl Global vs Faitlynhair.
--
-- Adds email_campaigns.merge_data (campaign-level tokens: sale discount, link,
-- end date → the static countdown) and seeds a new `sale_announcement` template.
--
-- Idempotent: the installer upserts on template_key; safe to re-run.
-- ============================================================

CREATE OR REPLACE FUNCTION shared.fn_install_premium_email_templates(p_schema text)
RETURNS void
LANGUAGE plpgsql
AS $func$
DECLARE
  v_subject text;
  v_pre     text;
  v_html    text;
  v_text    text;
BEGIN
  -- welcome
  v_subject := $pgh$Welcome to {{brand_name}}, {{first_name}} ✨$pgh$;
  v_pre     := $pgh$You're now part of the {{brand_name}} community — here's what to expect.$pgh$;
  v_html    := $pgh$<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light only">
<title>{{brand_name}}</title>
<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,500;0,600;0,700;1,500&display=swap');
  :root { color-scheme: light only; supported-color-schemes: light only; }
  body { margin:0; padding:0; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; }
  img { -ms-interpolation-mode:bicubic; }
  a { text-decoration:none; }
  @media only screen and (max-width:620px) {
    .pgh-card { width:100% !important; border-radius:0 !important; }
    .pgh-card td { padding-left:24px !important; padding-right:24px !important; }
  }
</style>
</head>
<body style="margin:0;padding:0;background-color:#F4EFE9">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;font-size:1px;line-height:1px;color:#F4EFE9">You're now part of the {{brand_name}} community — here's what to expect.&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;</div>
  <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#F4EFE9" style="background-color:#F4EFE9">
    <tr><td align="center" style="padding:32px 12px">
      <!--[if mso]><table role="presentation" width="600" border="0" cellspacing="0" cellpadding="0"><tr><td><![endif]-->
      <table role="presentation" class="pgh-card" width="600" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF" style="width:600px;max-width:600px;background-color:#FFFFFF;border-radius:10px;overflow:hidden;border:1px solid #ECE5DC">
<tr><td align="center" style="padding:34px 40px 22px 40px;border-bottom:1px solid #ECE5DC">
    <img src="{{logo_url}}" alt="{{brand_name}}" height="40" style="display:block;border:0;max-height:44px;width:auto" />
    <!--[if mso]>&nbsp;<![endif]-->
  </td></tr>
<tr><td style="padding:36px 40px 0px 40px"><div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:{{brand_color}}">Welcome to the house</div></td></tr>
<tr><td style="padding:12px 40px 0px 40px"><h1 style="margin:0;font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:30px;line-height:1.22;font-weight:600;color:#1A1212;letter-spacing:-0.2px">A warm welcome, {{first_name}}</h1></td></tr>
<tr><td style="padding:16px 40px 0px 40px"><p style="margin:0;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:15px;line-height:1.62;color:#1A1212">We're so glad you're here. {{brand_name}} is built on a simple belief — that the pieces you choose should feel considered, cared for, and made to last. Consider this your front-row seat.</p></td></tr>
<tr><td style="font-size:0;line-height:0;height:8px">&nbsp;</td></tr>
<tr><td style="padding:6px 40px">
    <table role="presentation" border="0" cellspacing="0" cellpadding="0"><tr>
      <td valign="top" style="font-size:16px;padding-right:12px;color:{{brand_color}}">✦</td>
      <td style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;line-height:1.5;color:#1A1212"><b>Curated quality</b> — every piece chosen with intention, never filler.</td>
    </tr></table>
  </td></tr>
<tr><td style="padding:6px 40px">
    <table role="presentation" border="0" cellspacing="0" cellpadding="0"><tr>
      <td valign="top" style="font-size:16px;padding-right:12px;color:{{brand_color}}">✦</td>
      <td style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;line-height:1.5;color:#1A1212"><b>Concierge care</b> — real people, ready when you need us.</td>
    </tr></table>
  </td></tr>
<tr><td style="padding:6px 40px">
    <table role="presentation" border="0" cellspacing="0" cellpadding="0"><tr>
      <td valign="top" style="font-size:16px;padding-right:12px;color:{{brand_color}}">✦</td>
      <td style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;line-height:1.5;color:#1A1212"><b>Member-first offers</b> — you'll hear about the good things first.</td>
    </tr></table>
  </td></tr>
<tr><td align="center" style="padding:30px 40px 8px 40px">
    <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="{{website_url}}" style="height:50px;v-text-anchor:middle;width:280px;" arcsize="9%" strokecolor="{{brand_color}}" fillcolor="{{brand_color}}"><w:anchorlock/><center style="color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;">Explore the collection</center></v:roundrect><![endif]-->
    <!--[if !mso]><!-- -->
    <a href="{{website_url}}" target="_blank" style="display:inline-block;background:{{brand_color}};color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;text-decoration:none;padding:16px 40px;border-radius:4px">Explore the collection</a>
    <!--<![endif]-->
  </td></tr>
<tr><td style="font-size:0;line-height:0;height:12px">&nbsp;</td></tr>
<tr><td style="padding:34px 40px 40px 40px;border-top:1px solid #ECE5DC" align="center">
    <div style="font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:17px;color:#1A1212;letter-spacing:0.5px">{{brand_name}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068;margin-top:8px">{{brand_address}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068">
      <a href="{{website_url}}" target="_blank" style="color:#7A7068;text-decoration:none">{{website_url}}</a>
      &nbsp;·&nbsp;
      <a href="mailto:{{support_email}}" style="color:#7A7068;text-decoration:none">{{support_email}}</a>
    </div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;line-height:1.7;color:#A89F96;margin-top:16px">
      You're receiving this because you're part of the {{brand_name}} community.<br/>
      <a href="{{unsubscribe_url}}" target="_blank" style="color:#A89F96;text-decoration:underline">Unsubscribe</a>
      &nbsp;·&nbsp; © {{year}} {{brand_legal_name}}
    </div>
  </td></tr>
      </table>
      <!--[if mso]></td></tr></table><![endif]-->
    </td></tr>
  </table>
</body>
</html>$pgh$;
  v_text    := $pgh$Welcome to {{brand_name}}, {{first_name}}.
We're so glad you're here. {{brand_name}} is built on a simple belief — that the pieces you choose should feel considered, cared for, and made to last.
Explore the collection: {{website_url}}
Questions? Just reply, or email {{support_email}}.
— {{brand_name}}$pgh$;
  EXECUTE format(
    'INSERT INTO %I.email_templates '
    || '(template_key, display_name, subject_line, preheader_text, html_body, '
    || ' plain_text_body, available_variables, category, status, is_system_template) '
    || 'VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,true) '
    || 'ON CONFLICT (template_key) DO UPDATE SET '
    || '  display_name=EXCLUDED.display_name, subject_line=EXCLUDED.subject_line, '
    || '  preheader_text=EXCLUDED.preheader_text, html_body=EXCLUDED.html_body, '
    || '  plain_text_body=EXCLUDED.plain_text_body, '
    || '  available_variables=EXCLUDED.available_variables, '
    || '  category=EXCLUDED.category, updated_at=now()',
    p_schema
  ) USING 'welcome', $pgh$Welcome$pgh$, v_subject, v_pre, v_html,
          v_text, ARRAY['customer_name','first_name']::text[], 'onboarding', 'approved';

  -- order_confirmation
  v_subject := $pgh$Your {{brand_name}} order {{order_number}} is confirmed$pgh$;
  v_pre     := $pgh$Thank you, {{first_name}} — we've received your order and we're on it.$pgh$;
  v_html    := $pgh$<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light only">
<title>{{brand_name}}</title>
<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,500;0,600;0,700;1,500&display=swap');
  :root { color-scheme: light only; supported-color-schemes: light only; }
  body { margin:0; padding:0; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; }
  img { -ms-interpolation-mode:bicubic; }
  a { text-decoration:none; }
  @media only screen and (max-width:620px) {
    .pgh-card { width:100% !important; border-radius:0 !important; }
    .pgh-card td { padding-left:24px !important; padding-right:24px !important; }
  }
</style>
</head>
<body style="margin:0;padding:0;background-color:#F4EFE9">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;font-size:1px;line-height:1px;color:#F4EFE9">Thank you, {{first_name}} — we've received your order and we're on it.&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;</div>
  <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#F4EFE9" style="background-color:#F4EFE9">
    <tr><td align="center" style="padding:32px 12px">
      <!--[if mso]><table role="presentation" width="600" border="0" cellspacing="0" cellpadding="0"><tr><td><![endif]-->
      <table role="presentation" class="pgh-card" width="600" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF" style="width:600px;max-width:600px;background-color:#FFFFFF;border-radius:10px;overflow:hidden;border:1px solid #ECE5DC">
<tr><td align="center" style="padding:34px 40px 22px 40px;border-bottom:1px solid #ECE5DC">
    <img src="{{logo_url}}" alt="{{brand_name}}" height="40" style="display:block;border:0;max-height:44px;width:auto" />
    <!--[if mso]>&nbsp;<![endif]-->
  </td></tr>
<tr><td style="padding:36px 40px 0px 40px"><div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:{{brand_color}}">Order confirmed</div></td></tr>
<tr><td style="padding:12px 40px 0px 40px"><h1 style="margin:0;font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:30px;line-height:1.22;font-weight:600;color:#1A1212;letter-spacing:-0.2px">Thank you, {{first_name}}</h1></td></tr>
<tr><td style="padding:16px 40px 0px 40px"><p style="margin:0;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:15px;line-height:1.62;color:#1A1212">Your order is confirmed and being prepared with care. We'll let you know the moment it's on its way.</p></td></tr>
<tr><td align="center" style="padding:22px 40px 0 40px">
    <table role="presentation" border="0" cellspacing="0" cellpadding="0"><tr>
      <td style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:18px;color:#A89F96;text-decoration:line-through;padding-right:14px">Order {{order_number}}</td>
      <td style="font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:30px;font-weight:700;color:{{brand_color}}">{{order_total}}</td>
    </tr></table>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;letter-spacing:1px;text-transform:uppercase;color:#7A7068;margin-top:8px">Order total</div>
  </td></tr>
<tr><td align="center" style="padding:30px 40px 8px 40px">
    <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="{{tracking_url}}" style="height:50px;v-text-anchor:middle;width:280px;" arcsize="9%" strokecolor="{{brand_color}}" fillcolor="{{brand_color}}"><w:anchorlock/><center style="color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;">Track your order</center></v:roundrect><![endif]-->
    <!--[if !mso]><!-- -->
    <a href="{{tracking_url}}" target="_blank" style="display:inline-block;background:{{brand_color}};color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;text-decoration:none;padding:16px 40px;border-radius:4px">Track your order</a>
    <!--<![endif]-->
  </td></tr>
<tr><td style="font-size:0;line-height:0;height:12px">&nbsp;</td></tr>
<tr><td style="padding:34px 40px 40px 40px;border-top:1px solid #ECE5DC" align="center">
    <div style="font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:17px;color:#1A1212;letter-spacing:0.5px">{{brand_name}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068;margin-top:8px">{{brand_address}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068">
      <a href="{{website_url}}" target="_blank" style="color:#7A7068;text-decoration:none">{{website_url}}</a>
      &nbsp;·&nbsp;
      <a href="mailto:{{support_email}}" style="color:#7A7068;text-decoration:none">{{support_email}}</a>
    </div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;line-height:1.7;color:#A89F96;margin-top:16px">
      You're receiving this because you're part of the {{brand_name}} community.<br/>
      <a href="{{unsubscribe_url}}" target="_blank" style="color:#A89F96;text-decoration:underline">Unsubscribe</a>
      &nbsp;·&nbsp; © {{year}} {{brand_legal_name}}
    </div>
  </td></tr>
      </table>
      <!--[if mso]></td></tr></table><![endif]-->
    </td></tr>
  </table>
</body>
</html>$pgh$;
  v_text    := $pgh$Thank you, {{first_name}} — your {{brand_name}} order {{order_number}} is confirmed.
Order total: {{order_total}}
Track your order: {{tracking_url}}
Need anything? Email {{support_email}}.
— {{brand_name}}$pgh$;
  EXECUTE format(
    'INSERT INTO %I.email_templates '
    || '(template_key, display_name, subject_line, preheader_text, html_body, '
    || ' plain_text_body, available_variables, category, status, is_system_template) '
    || 'VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,true) '
    || 'ON CONFLICT (template_key) DO UPDATE SET '
    || '  display_name=EXCLUDED.display_name, subject_line=EXCLUDED.subject_line, '
    || '  preheader_text=EXCLUDED.preheader_text, html_body=EXCLUDED.html_body, '
    || '  plain_text_body=EXCLUDED.plain_text_body, '
    || '  available_variables=EXCLUDED.available_variables, '
    || '  category=EXCLUDED.category, updated_at=now()',
    p_schema
  ) USING 'order_confirmation', $pgh$Order Confirmation$pgh$, v_subject, v_pre, v_html,
          v_text, ARRAY['customer_name','first_name','order_number','order_total','tracking_url']::text[], 'transactional', 'approved';

  -- shipped
  v_subject := $pgh$Your {{brand_name}} order {{order_number}} is on its way$pgh$;
  v_pre     := $pgh$Good news, {{first_name}} — your order has shipped.$pgh$;
  v_html    := $pgh$<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light only">
<title>{{brand_name}}</title>
<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,500;0,600;0,700;1,500&display=swap');
  :root { color-scheme: light only; supported-color-schemes: light only; }
  body { margin:0; padding:0; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; }
  img { -ms-interpolation-mode:bicubic; }
  a { text-decoration:none; }
  @media only screen and (max-width:620px) {
    .pgh-card { width:100% !important; border-radius:0 !important; }
    .pgh-card td { padding-left:24px !important; padding-right:24px !important; }
  }
</style>
</head>
<body style="margin:0;padding:0;background-color:#F4EFE9">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;font-size:1px;line-height:1px;color:#F4EFE9">Good news, {{first_name}} — your order has shipped.&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;</div>
  <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#F4EFE9" style="background-color:#F4EFE9">
    <tr><td align="center" style="padding:32px 12px">
      <!--[if mso]><table role="presentation" width="600" border="0" cellspacing="0" cellpadding="0"><tr><td><![endif]-->
      <table role="presentation" class="pgh-card" width="600" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF" style="width:600px;max-width:600px;background-color:#FFFFFF;border-radius:10px;overflow:hidden;border:1px solid #ECE5DC">
<tr><td align="center" style="padding:34px 40px 22px 40px;border-bottom:1px solid #ECE5DC">
    <img src="{{logo_url}}" alt="{{brand_name}}" height="40" style="display:block;border:0;max-height:44px;width:auto" />
    <!--[if mso]>&nbsp;<![endif]-->
  </td></tr>
<tr><td style="padding:36px 40px 0px 40px"><div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:{{brand_color}}">On its way</div></td></tr>
<tr><td style="padding:12px 40px 0px 40px"><h1 style="margin:0;font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:30px;line-height:1.22;font-weight:600;color:#1A1212;letter-spacing:-0.2px">It's shipping, {{first_name}}</h1></td></tr>
<tr><td style="padding:16px 40px 0px 40px"><p style="margin:0;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:15px;line-height:1.62;color:#1A1212">Your order {{order_number}} has left us and is on its way to you via {{courier_name}}. You can follow its journey any time.</p></td></tr>
<tr><td align="center" style="padding:30px 40px 8px 40px">
    <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="{{tracking_url}}" style="height:50px;v-text-anchor:middle;width:280px;" arcsize="9%" strokecolor="{{brand_color}}" fillcolor="{{brand_color}}"><w:anchorlock/><center style="color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;">Track shipment</center></v:roundrect><![endif]-->
    <!--[if !mso]><!-- -->
    <a href="{{tracking_url}}" target="_blank" style="display:inline-block;background:{{brand_color}};color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;text-decoration:none;padding:16px 40px;border-radius:4px">Track shipment</a>
    <!--<![endif]-->
  </td></tr>
<tr><td style="font-size:0;line-height:0;height:12px">&nbsp;</td></tr>
<tr><td style="padding:34px 40px 40px 40px;border-top:1px solid #ECE5DC" align="center">
    <div style="font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:17px;color:#1A1212;letter-spacing:0.5px">{{brand_name}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068;margin-top:8px">{{brand_address}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068">
      <a href="{{website_url}}" target="_blank" style="color:#7A7068;text-decoration:none">{{website_url}}</a>
      &nbsp;·&nbsp;
      <a href="mailto:{{support_email}}" style="color:#7A7068;text-decoration:none">{{support_email}}</a>
    </div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;line-height:1.7;color:#A89F96;margin-top:16px">
      You're receiving this because you're part of the {{brand_name}} community.<br/>
      <a href="{{unsubscribe_url}}" target="_blank" style="color:#A89F96;text-decoration:underline">Unsubscribe</a>
      &nbsp;·&nbsp; © {{year}} {{brand_legal_name}}
    </div>
  </td></tr>
      </table>
      <!--[if mso]></td></tr></table><![endif]-->
    </td></tr>
  </table>
</body>
</html>$pgh$;
  v_text    := $pgh$Good news, {{first_name}} — your {{brand_name}} order {{order_number}} is on its way via {{courier_name}}.
Track shipment: {{tracking_url}}
— {{brand_name}}$pgh$;
  EXECUTE format(
    'INSERT INTO %I.email_templates '
    || '(template_key, display_name, subject_line, preheader_text, html_body, '
    || ' plain_text_body, available_variables, category, status, is_system_template) '
    || 'VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,true) '
    || 'ON CONFLICT (template_key) DO UPDATE SET '
    || '  display_name=EXCLUDED.display_name, subject_line=EXCLUDED.subject_line, '
    || '  preheader_text=EXCLUDED.preheader_text, html_body=EXCLUDED.html_body, '
    || '  plain_text_body=EXCLUDED.plain_text_body, '
    || '  available_variables=EXCLUDED.available_variables, '
    || '  category=EXCLUDED.category, updated_at=now()',
    p_schema
  ) USING 'shipped', $pgh$Order Shipped$pgh$, v_subject, v_pre, v_html,
          v_text, ARRAY['customer_name','first_name','order_number','tracking_url','courier_name']::text[], 'transactional', 'approved';

  -- birthday
  v_subject := $pgh$Happy birthday, {{first_name}} — a little gift inside 🎁$pgh$;
  v_pre     := $pgh$A {{discount}}% birthday treat, just for you.$pgh$;
  v_html    := $pgh$<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light only">
<title>{{brand_name}}</title>
<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,500;0,600;0,700;1,500&display=swap');
  :root { color-scheme: light only; supported-color-schemes: light only; }
  body { margin:0; padding:0; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; }
  img { -ms-interpolation-mode:bicubic; }
  a { text-decoration:none; }
  @media only screen and (max-width:620px) {
    .pgh-card { width:100% !important; border-radius:0 !important; }
    .pgh-card td { padding-left:24px !important; padding-right:24px !important; }
  }
</style>
</head>
<body style="margin:0;padding:0;background-color:#F4EFE9">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;font-size:1px;line-height:1px;color:#F4EFE9">A {{discount}}% birthday treat, just for you.&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;</div>
  <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#F4EFE9" style="background-color:#F4EFE9">
    <tr><td align="center" style="padding:32px 12px">
      <!--[if mso]><table role="presentation" width="600" border="0" cellspacing="0" cellpadding="0"><tr><td><![endif]-->
      <table role="presentation" class="pgh-card" width="600" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF" style="width:600px;max-width:600px;background-color:#FFFFFF;border-radius:10px;overflow:hidden;border:1px solid #ECE5DC">
<tr><td align="center" style="padding:34px 40px 22px 40px;border-bottom:1px solid #ECE5DC">
    <img src="{{logo_url}}" alt="{{brand_name}}" height="40" style="display:block;border:0;max-height:44px;width:auto" />
    <!--[if mso]>&nbsp;<![endif]-->
  </td></tr>
<tr><td style="padding:36px 40px 0px 40px"><div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:{{brand_color}}">A gift for you</div></td></tr>
<tr><td style="padding:12px 40px 0px 40px"><h1 style="margin:0;font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:30px;line-height:1.22;font-weight:600;color:#1A1212;letter-spacing:-0.2px">Happy birthday, {{first_name}}</h1></td></tr>
<tr><td style="padding:16px 40px 0px 40px"><p style="margin:0;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:15px;line-height:1.62;color:#1A1212">Every celebration deserves something beautiful. Here's <b>{{discount}}% off</b> anything you've had your eye on — our way of marking your day.</p></td></tr>
<tr><td style="padding:26px 40px 6px 40px">
    <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr><td align="center" bgcolor="#1A1212" style="border-radius:6px;padding:18px 20px">
        <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:13px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#ffffff">⏳ Use code {{coupon_code}}</div>
        <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;letter-spacing:1px;color:#D9CFc6;margin-top:6px">{{discount}}% off — for a limited time</div>
      </td></tr>
    </table>
  </td></tr>
<tr><td align="center" style="padding:30px 40px 8px 40px">
    <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="{{website_url}}" style="height:50px;v-text-anchor:middle;width:280px;" arcsize="9%" strokecolor="{{brand_color}}" fillcolor="{{brand_color}}"><w:anchorlock/><center style="color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;">Treat yourself</center></v:roundrect><![endif]-->
    <!--[if !mso]><!-- -->
    <a href="{{website_url}}" target="_blank" style="display:inline-block;background:{{brand_color}};color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;text-decoration:none;padding:16px 40px;border-radius:4px">Treat yourself</a>
    <!--<![endif]-->
  </td></tr>
<tr><td style="font-size:0;line-height:0;height:12px">&nbsp;</td></tr>
<tr><td style="padding:34px 40px 40px 40px;border-top:1px solid #ECE5DC" align="center">
    <div style="font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:17px;color:#1A1212;letter-spacing:0.5px">{{brand_name}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068;margin-top:8px">{{brand_address}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068">
      <a href="{{website_url}}" target="_blank" style="color:#7A7068;text-decoration:none">{{website_url}}</a>
      &nbsp;·&nbsp;
      <a href="mailto:{{support_email}}" style="color:#7A7068;text-decoration:none">{{support_email}}</a>
    </div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;line-height:1.7;color:#A89F96;margin-top:16px">
      You're receiving this because you're part of the {{brand_name}} community.<br/>
      <a href="{{unsubscribe_url}}" target="_blank" style="color:#A89F96;text-decoration:underline">Unsubscribe</a>
      &nbsp;·&nbsp; © {{year}} {{brand_legal_name}}
    </div>
  </td></tr>
      </table>
      <!--[if mso]></td></tr></table><![endif]-->
    </td></tr>
  </table>
</body>
</html>$pgh$;
  v_text    := $pgh$Happy birthday, {{first_name}}!
Here's {{discount}}% off anything you've had your eye on — use code {{coupon_code}}.
Treat yourself: {{website_url}}
— {{brand_name}}$pgh$;
  EXECUTE format(
    'INSERT INTO %I.email_templates '
    || '(template_key, display_name, subject_line, preheader_text, html_body, '
    || ' plain_text_body, available_variables, category, status, is_system_template) '
    || 'VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,true) '
    || 'ON CONFLICT (template_key) DO UPDATE SET '
    || '  display_name=EXCLUDED.display_name, subject_line=EXCLUDED.subject_line, '
    || '  preheader_text=EXCLUDED.preheader_text, html_body=EXCLUDED.html_body, '
    || '  plain_text_body=EXCLUDED.plain_text_body, '
    || '  available_variables=EXCLUDED.available_variables, '
    || '  category=EXCLUDED.category, updated_at=now()',
    p_schema
  ) USING 'birthday', $pgh$Birthday Gift$pgh$, v_subject, v_pre, v_html,
          v_text, ARRAY['customer_name','first_name','coupon_code','discount']::text[], 'retention', 'approved';

  -- abandoned_cart
  v_subject := $pgh$Still thinking it over, {{first_name}}?$pgh$;
  v_pre     := $pgh$Your selection is saved — pick up right where you left off.$pgh$;
  v_html    := $pgh$<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light only">
<title>{{brand_name}}</title>
<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,500;0,600;0,700;1,500&display=swap');
  :root { color-scheme: light only; supported-color-schemes: light only; }
  body { margin:0; padding:0; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; }
  img { -ms-interpolation-mode:bicubic; }
  a { text-decoration:none; }
  @media only screen and (max-width:620px) {
    .pgh-card { width:100% !important; border-radius:0 !important; }
    .pgh-card td { padding-left:24px !important; padding-right:24px !important; }
  }
</style>
</head>
<body style="margin:0;padding:0;background-color:#F4EFE9">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;font-size:1px;line-height:1px;color:#F4EFE9">Your selection is saved — pick up right where you left off.&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;</div>
  <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#F4EFE9" style="background-color:#F4EFE9">
    <tr><td align="center" style="padding:32px 12px">
      <!--[if mso]><table role="presentation" width="600" border="0" cellspacing="0" cellpadding="0"><tr><td><![endif]-->
      <table role="presentation" class="pgh-card" width="600" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF" style="width:600px;max-width:600px;background-color:#FFFFFF;border-radius:10px;overflow:hidden;border:1px solid #ECE5DC">
<tr><td align="center" style="padding:34px 40px 22px 40px;border-bottom:1px solid #ECE5DC">
    <img src="{{logo_url}}" alt="{{brand_name}}" height="40" style="display:block;border:0;max-height:44px;width:auto" />
    <!--[if mso]>&nbsp;<![endif]-->
  </td></tr>
<tr><td style="padding:36px 40px 0px 40px"><div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:{{brand_color}}">You left something</div></td></tr>
<tr><td style="padding:12px 40px 0px 40px"><h1 style="margin:0;font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:30px;line-height:1.22;font-weight:600;color:#1A1212;letter-spacing:-0.2px">Your selection is waiting</h1></td></tr>
<tr><td style="padding:16px 40px 0px 40px"><p style="margin:0;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:15px;line-height:1.62;color:#1A1212">Good taste, {{first_name}}. The pieces in your bag are still here — but they're popular, and we can't hold them forever.</p></td></tr>
<tr><td align="center" style="padding:30px 40px 8px 40px">
    <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="{{cart_url}}" style="height:50px;v-text-anchor:middle;width:280px;" arcsize="9%" strokecolor="{{brand_color}}" fillcolor="{{brand_color}}"><w:anchorlock/><center style="color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;">Return to your bag</center></v:roundrect><![endif]-->
    <!--[if !mso]><!-- -->
    <a href="{{cart_url}}" target="_blank" style="display:inline-block;background:{{brand_color}};color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;text-decoration:none;padding:16px 40px;border-radius:4px">Return to your bag</a>
    <!--<![endif]-->
  </td></tr>
<tr><td style="font-size:0;line-height:0;height:12px">&nbsp;</td></tr>
<tr><td style="padding:34px 40px 40px 40px;border-top:1px solid #ECE5DC" align="center">
    <div style="font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:17px;color:#1A1212;letter-spacing:0.5px">{{brand_name}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068;margin-top:8px">{{brand_address}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068">
      <a href="{{website_url}}" target="_blank" style="color:#7A7068;text-decoration:none">{{website_url}}</a>
      &nbsp;·&nbsp;
      <a href="mailto:{{support_email}}" style="color:#7A7068;text-decoration:none">{{support_email}}</a>
    </div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;line-height:1.7;color:#A89F96;margin-top:16px">
      You're receiving this because you're part of the {{brand_name}} community.<br/>
      <a href="{{unsubscribe_url}}" target="_blank" style="color:#A89F96;text-decoration:underline">Unsubscribe</a>
      &nbsp;·&nbsp; © {{year}} {{brand_legal_name}}
    </div>
  </td></tr>
      </table>
      <!--[if mso]></td></tr></table><![endif]-->
    </td></tr>
  </table>
</body>
</html>$pgh$;
  v_text    := $pgh$Still thinking it over, {{first_name}}?
The pieces in your bag are still saved — return any time: {{cart_url}}
— {{brand_name}}$pgh$;
  EXECUTE format(
    'INSERT INTO %I.email_templates '
    || '(template_key, display_name, subject_line, preheader_text, html_body, '
    || ' plain_text_body, available_variables, category, status, is_system_template) '
    || 'VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,true) '
    || 'ON CONFLICT (template_key) DO UPDATE SET '
    || '  display_name=EXCLUDED.display_name, subject_line=EXCLUDED.subject_line, '
    || '  preheader_text=EXCLUDED.preheader_text, html_body=EXCLUDED.html_body, '
    || '  plain_text_body=EXCLUDED.plain_text_body, '
    || '  available_variables=EXCLUDED.available_variables, '
    || '  category=EXCLUDED.category, updated_at=now()',
    p_schema
  ) USING 'abandoned_cart', $pgh$Abandoned Cart$pgh$, v_subject, v_pre, v_html,
          v_text, ARRAY['customer_name','first_name','cart_url','items_count']::text[], 'retention', 'approved';

  -- sale_announcement
  v_subject := $pgh$Up to {{discount}}% off — the {{brand_name}} sale is here$pgh$;
  v_pre     := $pgh${{deadline_phrase}} · our biggest savings of the season end {{sale_end_display}}.$pgh$;
  v_html    := $pgh$<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light only">
<title>{{brand_name}}</title>
<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,500;0,600;0,700;1,500&display=swap');
  :root { color-scheme: light only; supported-color-schemes: light only; }
  body { margin:0; padding:0; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; }
  img { -ms-interpolation-mode:bicubic; }
  a { text-decoration:none; }
  @media only screen and (max-width:620px) {
    .pgh-card { width:100% !important; border-radius:0 !important; }
    .pgh-card td { padding-left:24px !important; padding-right:24px !important; }
  }
</style>
</head>
<body style="margin:0;padding:0;background-color:#F4EFE9">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;font-size:1px;line-height:1px;color:#F4EFE9">{{deadline_phrase}} · our biggest savings of the season end {{sale_end_display}}.&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;</div>
  <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#F4EFE9" style="background-color:#F4EFE9">
    <tr><td align="center" style="padding:32px 12px">
      <!--[if mso]><table role="presentation" width="600" border="0" cellspacing="0" cellpadding="0"><tr><td><![endif]-->
      <table role="presentation" class="pgh-card" width="600" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF" style="width:600px;max-width:600px;background-color:#FFFFFF;border-radius:10px;overflow:hidden;border:1px solid #ECE5DC">
<tr><td align="center" style="padding:34px 40px 22px 40px;border-bottom:1px solid #ECE5DC">
    <img src="{{logo_url}}" alt="{{brand_name}}" height="40" style="display:block;border:0;max-height:44px;width:auto" />
    <!--[if mso]>&nbsp;<![endif]-->
  </td></tr>
<tr><td style="padding:36px 40px 0px 40px"><div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:{{brand_color}}">Private sale · members first</div></td></tr>
<tr><td style="padding:12px 40px 0px 40px"><h1 style="margin:0;font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:30px;line-height:1.22;font-weight:600;color:#1A1212;letter-spacing:-0.2px">Up to {{discount}}% off, {{first_name}}</h1></td></tr>
<tr><td style="padding:16px 40px 0px 40px"><p style="margin:0;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:15px;line-height:1.62;color:#1A1212">The {{brand_name}} sale is officially open. For a limited time, take <b>up to {{discount}}% off</b> across the collection — the same craftsmanship, at a price that rarely comes around.</p></td></tr>
<tr><td style="padding:26px 40px 6px 40px">
    <table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr><td align="center" bgcolor="#1A1212" style="border-radius:6px;padding:18px 20px">
        <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:13px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#ffffff">⏳ {{deadline_phrase}}</div>
        <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;letter-spacing:1px;color:#D9CFc6;margin-top:6px">Sale ends {{sale_end_display}}</div>
      </td></tr>
    </table>
  </td></tr>
<tr><td style="font-size:0;line-height:0;height:6px">&nbsp;</td></tr>
<tr><td style="padding:6px 40px">
    <table role="presentation" border="0" cellspacing="0" cellpadding="0"><tr>
      <td valign="top" style="font-size:16px;padding-right:12px;color:{{brand_color}}">✦</td>
      <td style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;line-height:1.5;color:#1A1212"><b>Up to {{discount}}% off</b> — across the pieces you've been waiting for.</td>
    </tr></table>
  </td></tr>
<tr><td style="padding:6px 40px">
    <table role="presentation" border="0" cellspacing="0" cellpadding="0"><tr>
      <td valign="top" style="font-size:16px;padding-right:12px;color:{{brand_color}}">✦</td>
      <td style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;line-height:1.5;color:#1A1212"><b>Members first</b> — you're seeing this before anyone else.</td>
    </tr></table>
  </td></tr>
<tr><td style="padding:6px 40px">
    <table role="presentation" border="0" cellspacing="0" cellpadding="0"><tr>
      <td valign="top" style="font-size:16px;padding-right:12px;color:{{brand_color}}">✦</td>
      <td style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;line-height:1.5;color:#1A1212"><b>While they last</b> — best sellers move fast at these prices.</td>
    </tr></table>
  </td></tr>
<tr><td align="center" style="padding:30px 40px 8px 40px">
    <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="{{sale_url}}" style="height:50px;v-text-anchor:middle;width:280px;" arcsize="9%" strokecolor="{{brand_color}}" fillcolor="{{brand_color}}"><w:anchorlock/><center style="color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;">Shop the sale</center></v:roundrect><![endif]-->
    <!--[if !mso]><!-- -->
    <a href="{{sale_url}}" target="_blank" style="display:inline-block;background:{{brand_color}};color:#ffffff;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:14px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;text-decoration:none;padding:16px 40px;border-radius:4px">Shop the sale</a>
    <!--<![endif]-->
  </td></tr>
<tr><td style="padding:18px 40px 0px 40px"><p style="margin:0;font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:15px;line-height:1.62;color:#7A7068">Don't wait — {{deadline_phrase}}. When it's gone, it's gone.</p></td></tr>
<tr><td style="font-size:0;line-height:0;height:12px">&nbsp;</td></tr>
<tr><td style="padding:34px 40px 40px 40px;border-top:1px solid #ECE5DC" align="center">
    <div style="font-family:'Playfair Display', Georgia, 'Times New Roman', serif;font-size:17px;color:#1A1212;letter-spacing:0.5px">{{brand_name}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068;margin-top:8px">{{brand_address}}</div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:12px;line-height:1.7;color:#7A7068">
      <a href="{{website_url}}" target="_blank" style="color:#7A7068;text-decoration:none">{{website_url}}</a>
      &nbsp;·&nbsp;
      <a href="mailto:{{support_email}}" style="color:#7A7068;text-decoration:none">{{support_email}}</a>
    </div>
    <div style="font-family:'Montserrat', 'Helvetica Neue', Arial, sans-serif;font-size:11px;line-height:1.7;color:#A89F96;margin-top:16px">
      You're receiving this because you're part of the {{brand_name}} community.<br/>
      <a href="{{unsubscribe_url}}" target="_blank" style="color:#A89F96;text-decoration:underline">Unsubscribe</a>
      &nbsp;·&nbsp; © {{year}} {{brand_legal_name}}
    </div>
  </td></tr>
      </table>
      <!--[if mso]></td></tr></table><![endif]-->
    </td></tr>
  </table>
</body>
</html>$pgh$;
  v_text    := $pgh${{first_name}}, the {{brand_name}} sale is here — up to {{discount}}% off.
{{deadline_phrase}} · sale ends {{sale_end_display}}.
Shop now: {{sale_url}}
Members first. While they last.
— {{brand_name}}$pgh$;
  EXECUTE format(
    'INSERT INTO %I.email_templates '
    || '(template_key, display_name, subject_line, preheader_text, html_body, '
    || ' plain_text_body, available_variables, category, status, is_system_template) '
    || 'VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,true) '
    || 'ON CONFLICT (template_key) DO UPDATE SET '
    || '  display_name=EXCLUDED.display_name, subject_line=EXCLUDED.subject_line, '
    || '  preheader_text=EXCLUDED.preheader_text, html_body=EXCLUDED.html_body, '
    || '  plain_text_body=EXCLUDED.plain_text_body, '
    || '  available_variables=EXCLUDED.available_variables, '
    || '  category=EXCLUDED.category, updated_at=now()',
    p_schema
  ) USING 'sale_announcement', $pgh$Sale Announcement$pgh$, v_subject, v_pre, v_html,
          v_text, ARRAY['customer_name','first_name','discount','sale_url','sale_end_display','deadline_phrase','days_left']::text[], 'marketing', 'approved';
END;
$func$;

-- Apply to every existing brand schema; add the campaign-level merge_data
-- column the sale countdown/CTA rides on.
DO $do$
DECLARE
  sch text;
BEGIN
  FOR sch IN
    SELECT n.nspname
      FROM pg_namespace n
      JOIN information_schema.tables t
        ON t.table_schema = n.nspname AND t.table_name = 'email_templates'
     WHERE n.nspname NOT IN ('template')
  LOOP
    EXECUTE format(
      'ALTER TABLE %I.email_campaigns '
      || 'ADD COLUMN IF NOT EXISTS merge_data jsonb NOT NULL DEFAULT ''{}''::jsonb',
      sch
    );
    PERFORM shared.fn_install_premium_email_templates(sch);
    RAISE NOTICE 'premium email templates installed on %', sch;
  END LOOP;
END
$do$;

-- ============================================================
-- Verify
--   SELECT template_key, length(html_body) FROM pixiegirl.email_templates
--    WHERE is_system_template ORDER BY template_key;
-- ============================================================
