/**
 * Dashboards (V2.2 §6.20) — Excel export.
 *
 * One styled workbook per domain dashboard, honouring the exact period the
 * user was looking at:
 *   • Summary        — title banner, period meta, KPI block (with Δ%).
 *   • one sheet per chart   — its breakdown/series as a table.
 *   • one sheet per detail  — the full drill-down dataset (capped).
 *
 * Access: the route requires dashboards.export (matrix; org rights never
 * export) and the metrics service re-asserts the domain gate, so a role that
 * cannot open the Finance tab can never export it. Cost tiles are already
 * stripped from the payload for non-cost roles — what you can't see, you
 * can't export.
 *
 * Workbook builders are pure (payload in → Buffer out) for DB-free tests.
 */

"use strict";

const xl = require("../../services/excel/workbook");
const metricsService = require("./dashboards.metrics.service");
const registry = require("./dashboards.domains");
const details = require("./dashboards.details.repo");
const { DETAIL_COLUMNS } = require("./dashboards.columns");
const { NotFoundError } = require("../../utils/errors");

const EXPORT_ROW_CAP = 5000;

// Money-ish keys in chart breakdowns (everything else numeric is a count).
const MONEY_KEYS = new Set([
  "value",
  "amount",
  "revenue",
  "fees",
  "gross",
  "net",
  "spend",
  "ad_return",
]);
// Charts whose `value` is a count, not money.
const COUNT_VALUE_CHARTS = new Set([
  "orders_by_channel",
  "acquisition_by_source",
  "churn_bands",
  "status_breakdown",
  "device_breakdown",
  "currency_breakdown",
  "tier_distribution",
  "top_coupons",
  "courier_performance",
  "engagement_by_platform",
  "sell_through_by_channel",
  "top_sources",
]);

function chartColumns(chart) {
  if (chart.series) {
    return [
      { key: "x", label: "Period", format: "text" },
      ...chart.series.map((s) => ({
        key: s.key,
        label: s.label,
        format: MONEY_KEYS.has(s.key) || s.key === "current" || s.key === "previous" ? "money" : "num",
      })),
    ];
  }
  const rows = chart.slices || chart.steps || [];
  const sample = rows[0] || { label: "", value: 0 };
  return Object.keys(sample).map((key) => {
    if (key === "label") return { key, label: "Label", format: "text" };
    const money = MONEY_KEYS.has(key) && !(key === "value" && COUNT_VALUE_CHARTS.has(chart.key));
    return {
      key,
      label: key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
      format: money ? "money" : "num",
    };
  });
}

function chartRows(chart) {
  if (chart.series) {
    const byX = new Map();
    for (const s of chart.series) {
      for (const p of s.points) {
        const row = byX.get(p.x) || { x: p.x };
        row[s.key] = p.y;
        byX.set(p.x, row);
      }
    }
    return [...byX.values()];
  }
  return chart.slices || chart.steps || [];
}

/** Pure: domain payload (+ full detail sets) → styled workbook. */
function buildDomainWorkbook({
  brandLabel,
  payload,
  detailSets = [],
  generatedBy = null,
  generatedAt = new Date(),
}) {
  const wb = xl.newWorkbook();
  const ws = wb.addWorksheet("Summary");
  const meta = [
    ["Business", brandLabel],
    [
      "Period",
      `${xl.fmtDay(payload.period.from)} → ${xl.fmtDay(payload.period.to)}`,
    ],
    [
      "Compared to",
      `${xl.fmtDay(payload.previous_period.from)} → ${xl.fmtDay(payload.previous_period.to)}`,
    ],
    ["Generated", xl.fmtDate(generatedAt)],
  ];
  if (generatedBy) meta.push(["Generated by", generatedBy]);
  const next = xl.addTitleBlock(
    ws,
    `${payload.label} Dashboard`,
    "Pixie Girl Hub · §6.20 Dashboards & Reports",
    meta,
  );
  xl.addKpiRows(ws, next, payload.kpis);

  for (const chart of payload.charts) {
    const rows = chartRows(chart);
    if (!rows.length) continue;
    xl.addManifestTable(wb, chart.label, chartColumns(chart), rows);
  }
  for (const set of detailSets) {
    xl.addManifestTable(wb, set.label, set.columns, set.rows);
  }
  return wb;
}

/** GET /dashboards/domains/:key/export → { buffer, filename }. */
async function exportDomain({ brand, user, key, from, to }) {
  const domainDef = registry.getDomain(key);
  if (!domainDef) throw new NotFoundError("Dashboard domain");

  // Same payload the user saw (gates + cost stripping inside).
  const payload = await metricsService.domainData({ brand, user, key, from, to });

  const detailSets = [];
  const detailFns = details.DETAILS[key] || {};
  for (const [detailKey, def] of Object.entries(domainDef.details || {})) {
    const fn = detailFns[detailKey];
    if (!fn) continue;
    const { rows } = await fn({
      brand,
      from: payload.period.from,
      to: payload.period.to,
      filters: {},
      limit: EXPORT_ROW_CAP,
      offset: 0,
    });
    detailSets.push({
      label: def.label,
      columns: DETAIL_COLUMNS[key][detailKey] || [],
      rows,
    });
  }

  const wb = buildDomainWorkbook({
    brandLabel: brand,
    payload,
    detailSets,
    generatedBy: user.email || user.user_id,
  });
  const stamp = (iso) => xl.fmtDay(iso).replace(/-/g, "");
  const filename = `${brand}-${key}-dashboard-${stamp(payload.period.from)}-${stamp(payload.period.to)}.xlsx`;
  return { buffer: await xl.toBuffer(wb), filename };
}

/**
 * Report run → workbook (GET /dashboards/report-runs/:id/excel). Flattens the
 * run's stored outputs: object payloads become label/value rows, arrays of
 * objects become tables.
 */
function buildReportRunWorkbook({ run }) {
  const wb = xl.newWorkbook();
  const ws = wb.addWorksheet("Summary");
  const title = run.template_name || "Report";
  const next = xl.addTitleBlock(ws, title, "Pixie Girl Hub · weekly auto-report", [
    ["Run", run.run_number],
    [
      "Period",
      `${xl.fmtDay(run.period_start)} → ${xl.fmtDay(run.period_end)}`,
    ],
    ["Status", run.status],
    ["Generated", xl.fmtDate(run.created_at)],
  ]);
  void next;

  let sheetIndex = 1;
  for (const output of run.outputs || []) {
    const payload = output.inline_payload;
    if (!payload || typeof payload !== "object") continue;
    for (const [sectionKey, value] of Object.entries(payload)) {
      const name = `${sheetIndex} ${sectionKey.replace(/_/g, " ")}`;
      if (Array.isArray(value) && value.length && typeof value[0] === "object") {
        const columns = Object.keys(value[0]).map((k) => ({
          key: k,
          label: k.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
          format:
            /_ngn$|amount|revenue|total/.test(k) && typeof value[0][k] !== "object"
              ? "money"
              : "text",
        }));
        xl.addManifestTable(wb, name, columns, value);
        sheetIndex += 1;
      } else if (value !== null && typeof value === "object") {
        const rows = Object.entries(value)
          .filter(([, v]) => v === null || typeof v !== "object")
          .map(([k, v]) => ({
            metric: k.replace(/_/g, " "),
            value: v === null || v === undefined ? "" : String(v),
          }));
        if (rows.length) {
          xl.addManifestTable(
            wb,
            name,
            [
              { key: "metric", label: "Metric", format: "text" },
              { key: "value", label: "Value", format: "text" },
            ],
            rows,
          );
          sheetIndex += 1;
        }
      }
    }
  }
  return wb;
}

async function exportReportRun({ run }) {
  const wb = buildReportRunWorkbook({ run });
  const filename = `${(run.run_number || "report").toLowerCase()}.xlsx`;
  return { buffer: await xl.toBuffer(wb), filename };
}

module.exports = {
  exportDomain,
  exportReportRun,
  // Pure builders exposed for unit tests (no DB needed).
  _internals: { buildDomainWorkbook, buildReportRunWorkbook, chartColumns, chartRows },
};
