"use strict";

// Regression guard for the FLH-SO-0059 amount discrepancy.
//
// A USD order (sold at the campaign's locked ₦/$ rate) had its pay link
// generated by the admin "Send Pay Link" button, which passes NO currency.
// The service used to default to "NGN", so it built a Nomba checkout in Naira;
// Nomba then reconverted that Naira total at its own live rate when the buyer
// paid by international card, charging $708.25 instead of the quoted $764.
//
// The fix: when no currency is supplied, settle in the order's own
// display_currency and convert at the order's LOCKED fx_rate_used. These tests
// assert the gateway receives USD + the whole-dollar figure, and that NGN
// orders still settle in Naira.

const ORDER_USD = {
  order_id: "ord-usd",
  order_number: "FLH-SO-0059",
  status: "pending",
  contact_id: "contact-1",
  sales_campaign_id: "camp-1",
  total_ngn: "992400.00",
  amount_paid_ngn: "0.00",
  display_currency: "USD",
  fx_rate_used: "1300", // locked at placement → ₦992,400 ÷ 1,300 = $763.38 → $764
};

const ORDER_NGN = {
  order_id: "ord-ngn",
  order_number: "FLH-SO-0060",
  status: "pending",
  contact_id: "contact-1",
  sales_campaign_id: null,
  total_ngn: "500000.00",
  amount_paid_ngn: "0.00",
  display_currency: null,
  fx_rate_used: null,
};

let mockOrder = ORDER_USD;
const mockNombaCalls = [];
const mockChainCalls = [];

jest.mock("../../../src/modules/sales/sales.repo", () => ({
  findById: jest.fn(async () => mockOrder),
  findByPublicToken: jest.fn(async () => null),
  findByOrderNumber: jest.fn(async () => null),
}));

jest.mock("../../../src/modules/sales_campaigns/campaigns.repo", () => ({
  // Campaign rate intentionally DIFFERS from the order's locked rate to prove
  // we charge the locked fx_rate_used, not the (mutable) live campaign rate.
  findById: jest.fn(async () => ({ ngn_per_usd_rate: 1401 })),
}));

jest.mock("../../../src/modules/business_setup/payment-gateways.service", () => ({
  getActiveChain: jest.fn(async ({ currency }) => {
    mockChainCalls.push(currency);
    return [{ provider: "nomba", credentials: { client_id: "c" } }];
  }),
}));

jest.mock("../../../src/services/nomba.service", () => ({
  initializePayment: jest.fn(async (args) => {
    mockNombaCalls.push(args);
    return { data: { checkoutLink: "https://pay.nomba.com/checkout/xyz" } };
  }),
}));

jest.mock("../../../src/services/paystack.service", () => ({}));
jest.mock("../../../src/services/opay.service", () => ({}));
jest.mock("../../../src/services/stripe.service", () => ({}));

jest.mock("../../../src/config/database", () => ({
  query: jest.fn(async () => ({ rows: [{ email: "buyer@example.com" }] })),
}));

jest.mock("../../../src/config/env", () => ({
  config: { APP_URL: "https://hub.example.com" },
}));

const paymentLink = require("../../../src/modules/sales/payment-link.service");

beforeEach(() => {
  mockNombaCalls.length = 0;
  mockChainCalls.length = 0;
});

describe("createPaymentLink — settlement currency defaults to the order", () => {
  test("USD order with no currency → Nomba charged in USD at the locked rate", async () => {
    mockOrder = ORDER_USD;
    await paymentLink.createPaymentLink({
      brand: "faitlynhair",
      order_id: ORDER_USD.order_id,
      amount_ngn: 992400,
      // currency intentionally omitted — mimics the admin "Send Pay Link" button
    });

    expect(mockNombaCalls).toHaveLength(1);
    // Whole-dollar figure at the ORDER's locked 1,300 rate, NOT the 1,401
    // campaign rate (which would give $709) and NOT a Naira figure.
    expect(mockNombaCalls[0].currency).toBe("USD");
    expect(mockNombaCalls[0].amount).toBe("764");
    // The gateway chain must be routed by USD, not the default NGN rail.
    expect(mockChainCalls).toContain("USD");
  });

  test("NGN order with no currency → Nomba charged the full Naira total", async () => {
    mockOrder = ORDER_NGN;
    await paymentLink.createPaymentLink({
      brand: "faitlynhair",
      order_id: ORDER_NGN.order_id,
      amount_ngn: 500000,
    });

    expect(mockNombaCalls).toHaveLength(1);
    expect(mockNombaCalls[0].currency).toBe("NGN");
    expect(mockNombaCalls[0].amount).toBe("500000.00");
    expect(mockChainCalls).toContain("NGN");
  });

  test("explicit currency still wins over the order default", async () => {
    mockOrder = ORDER_USD;
    await paymentLink.createPaymentLink({
      brand: "faitlynhair",
      order_id: ORDER_USD.order_id,
      amount_ngn: 992400,
      currency: "NGN",
    });
    expect(mockNombaCalls[0].currency).toBe("NGN");
    expect(mockNombaCalls[0].amount).toBe("992400.00");
  });
});
