import {
  Palette,
  LayoutGrid,
  Users,
  ShoppingBag,
  CreditCard,
  Truck,
  Package,
  Factory,
  FileText,
  BookOpen,
  Wallet,
  UserCog,
  Megaphone,
  MessageCircle,
  Calendar,
  CheckSquare,
  BarChart3,
  Mail,
  Heart,
  Building2,
  Settings,
  ShieldCheck,
  Share2,
  Vault,
  Landmark,
  Sparkles,
  Layers,
  HelpCircle,
} from "lucide-react";

export interface AppModule {
  key: string;
  label: string;
  description: string;
  icon: typeof LayoutGrid;
  route: string;
  badgeKey?: string; // server-driven counter; resolved in HubHome
  accent: "gold" | "rose" | "sage" | "mixed";
  group: "main" | "finance" | "people" | "ops" | "system";
  // Restrict this module/tile to specific businesses. Omit = all businesses.
  businesses?: string[];
  // Backend permission module(s) that unlock this tile — the user needs
  // 'view' on at least one of them (see useVisibleModules). Keys MUST
  // match MODULE_CATALOGUE in shared/permissions/permissions.service.js.
  permissionModule?: string | string[];
  // Personal-workspace tiles every signed-in user may see.
  alwaysVisible?: boolean;
  // Global default rank for the top-10 grid (1 = first). Modules
  // without a defaultPriority live in the "More" section unless a
  // role default or user pin promotes them. The daily-touch test:
  // "does someone at Orika open this daily or several times a week?"
  defaultPriority?: number;
}

/** Maximum modules in the priority grid / sidebar priority group. */
export const NAV_PRIORITY_MAX = 10;

export const HUB_MODULES: AppModule[] = [
  {
    key: "dashboard",
    defaultPriority: 1,
    permissionModule: "dashboards",
    label: "Dashboard",
    description: "Live metrics across all businesses",
    icon: LayoutGrid,
    route: "/dashboard",
    accent: "gold",
    group: "main",
  },
  {
    key: "crm",
    defaultPriority: 4,
    permissionModule: "crm",
    label: "CRM",
    description: "Customer relationships",
    icon: Users,
    route: "/crm",
    badgeKey: "new_leads",
    accent: "rose",
    group: "main",
  },
  {
    key: "sales",
    defaultPriority: 3,
    permissionModule: "sales",
    label: "Sales",
    description: "Orders & quotations",
    icon: ShoppingBag,
    route: "/sales",
    accent: "gold",
    group: "main",
  },
  {
    key: "pos",
    defaultPriority: 2,
    permissionModule: "pos",
    label: "POS",
    description: "In-store point of sale",
    icon: CreditCard,
    route: "/pos",
    accent: "gold",
    group: "main",
  },
  {
    key: "logistics",
    defaultPriority: 7,
    permissionModule: "logistics",
    label: "Logistics",
    description: "Deliveries & shipping",
    icon: Truck,
    route: "/logistics",
    badgeKey: "in_transit",
    accent: "sage",
    group: "ops",
  },
  {
    key: "stock",
    defaultPriority: 6,
    permissionModule: "stock",
    label: "Stock & Inv",
    description: "Inventory across locations",
    icon: Package,
    route: "/stock",
    accent: "sage",
    group: "ops",
  },
  {
    key: "purchasing",
    permissionModule: "purchasing",
    label: "Procurement",
    description: "RFQ · PO · GRN · Bills",
    icon: Factory,
    route: "/procurement",
    badgeKey: "pending_pos",
    accent: "sage",
    group: "ops",
  },
  {
    key: "invoicing",
    defaultPriority: 8,
    permissionModule: "invoicing",
    label: "Invoices",
    description: "Issue & track invoices",
    icon: FileText,
    route: "/invoicing",
    badgeKey: "overdue",
    accent: "gold",
    group: "finance",
  },
  {
    key: "accounting",
    permissionModule: "accounting",
    label: "Accounting",
    description: "Chart of accounts, ledgers",
    icon: BookOpen,
    route: "/accounting",
    accent: "gold",
    group: "finance",
  },
  {
    key: "tax",
    permissionModule: "tax",
    label: "Tax Center",
    description: "VAT, WHT, PAYE & CIT filing",
    icon: Landmark,
    route: "/tax",
    accent: "gold",
    group: "finance",
  },
  {
    key: "expenses",
    defaultPriority: 9,
    permissionModule: "expenses",
    label: "Expenses",
    description: "Submissions & approvals",
    icon: Wallet,
    route: "/expenses",
    badgeKey: "awaiting_approval",
    accent: "gold",
    group: "finance",
  },
  {
    key: "payroll",
    permissionModule: "payroll",
    label: "Payroll",
    description: "Staff salaries & payslips",
    icon: UserCog,
    route: "/payroll",
    accent: "gold",
    group: "people",
  },
  {
    key: "staff",
    permissionModule: "staff",
    label: "HR & Staff",
    description: "Team profiles & directory",
    icon: Users,
    route: "/staff",
    accent: "rose",
    group: "people",
  },
  {
    key: "contacts",
    permissionModule: "crm",
    label: "Contacts",
    description: "Shared address book",
    icon: Mail,
    route: "/contacts",
    accent: "rose",
    group: "people",
  },
  {
    key: "messaging",
    permissionModule: "messaging",
    label: "Messaging",
    description: "WhatsApp, email, SMS",
    icon: MessageCircle,
    route: "/messaging",
    badgeKey: "unread",
    accent: "rose",
    group: "people",
  },
  {
    key: "campaigns",
    permissionModule: "campaigns",
    label: "Campaigns",
    description: "Marketing & promotions",
    icon: Megaphone,
    route: "/campaigns",
    accent: "rose",
    group: "ops",
  },
  {
    key: "sales-campaigns",
    permissionModule: "sales_campaigns",
    label: "Sales Campaigns",
    description: "Landing pages & storefronts",
    icon: Share2,
    route: "/sales-campaigns",
    accent: "rose",
    group: "ops",
  },
  {
    key: "workspace",
    alwaysVisible: true,
    label: "Workspace",
    description: "Personal notes & scratch area",
    icon: Layers,
    route: "/workspace",
    accent: "gold",
    group: "main",
  },
  {
    key: "social",
    permissionModule: "social",
    label: "Social",
    description: "Connected channels & posts",
    icon: Heart,
    route: "/social",
    accent: "rose",
    group: "ops",
  },
  {
    key: "loyalty",
    permissionModule: "loyalty",
    label: "Loyalty",
    description: "Tiers, points & rewards",
    icon: Heart,
    route: "/loyalty",
    accent: "rose",
    group: "people",
  },
  {
    key: "catalogue",
    defaultPriority: 5,
    permissionModule: "catalogue",
    label: "Catalogue",
    description: "Products · Categories · Locations",
    icon: Package,
    route: "/catalogue",
    accent: "sage",
    group: "ops",
  },
  {
    key: "retail-partners",
    permissionModule: "retail_partners",
    label: "Retail Partners",
    description: "Consignment & wholesale partners",
    icon: Building2,
    route: "/retail-partners",
    accent: "sage",
    group: "ops",
  },
  {
    key: "calendar",
    permissionModule: "calendar",
    label: "Calendar",
    description: "Shared schedule",
    icon: Calendar,
    route: "/calendar",
    badgeKey: "today",
    accent: "gold",
    group: "main",
  },
  {
    key: "tasks",
    permissionModule: "tasks",
    label: "Tasks",
    description: "Personal & team to-dos",
    icon: CheckSquare,
    route: "/tasks",
    badgeKey: "open",
    accent: "gold",
    group: "main",
  },
  {
    key: "reports",
    defaultPriority: 10,
    permissionModule: "reports",
    label: "Reports",
    description: "Standard & custom reports",
    icon: BarChart3,
    route: "/reports",
    accent: "gold",
    group: "finance",
  },
  {
    key: "settings",
    permissionModule: "settings",
    label: "Settings",
    description: "Business config, RBAC, integrations",
    icon: Settings,
    route: "/settings",
    accent: "mixed",
    group: "system",
  },
  {
    key: "security",
    permissionModule: ["security", "audit"],
    label: "Security",
    description: "Audit log & sessions",
    icon: ShieldCheck,
    route: "/security",
    accent: "mixed",
    group: "system",
  },
  {
    key: "documents",
    permissionModule: "documents",
    label: "Document Vault",
    description: "Tamper-proof document archive",
    icon: Vault,
    route: "/documents",
    accent: "gold",
    group: "system",
  },
  {
    key: "help",
    permissionModule: "help",
    label: "Help Center",
    description: "Guides, workflows & FAQs",
    icon: HelpCircle,
    route: "/help",
    accent: "gold",
    group: "system",
  },
];

export const SETTINGS_SUBMODULES: AppModule[] = [
  {
    key: "appearance",
    permissionModule: "settings",
    label: "Appearance",
    description: "White-label: product name, fonts, colour theme",
    icon: Palette,
    route: "/settings/appearance",
    accent: "gold",
    group: "system",
  },
  {
    key: "business-setup",
    permissionModule: "settings",
    label: "Business Setup",
    description: "Profile, branding, identity per business",
    icon: Building2,
    route: "/settings/business-setup",
    accent: "gold",
    group: "system",
  },
  {
    key: "bank-accounts",
    permissionModule: "settings",
    label: "Bank Accounts",
    description: "Bank accounts per business",
    icon: Wallet,
    route: "/settings/bank-accounts",
    accent: "sage",
    group: "system",
  },
  {
    key: "tax-rates",
    permissionModule: "settings",
    label: "Tax Rates",
    description: "VAT, WHT, PAYE & more",
    icon: FileText,
    route: "/settings/tax-rates",
    accent: "sage",
    group: "system",
  },
  {
    key: "currency-rates",
    permissionModule: "settings",
    label: "Currency Rates",
    description: "FX rates & manual overrides",
    icon: BarChart3,
    route: "/settings/currency-rates",
    accent: "gold",
    group: "system",
  },
  {
    key: "custom-fields",
    permissionModule: "settings",
    label: "Custom Fields",
    description: "Per-entity field definitions",
    icon: LayoutGrid,
    route: "/settings/custom-fields",
    accent: "rose",
    group: "system",
  },
  {
    key: "pipeline-stages",
    permissionModule: "settings",
    label: "Pipeline Stages",
    description: "CRM & sales pipeline definitions",
    icon: ShoppingBag,
    route: "/settings/pipeline-stages",
    accent: "rose",
    group: "system",
  },
  {
    key: "document-numbering",
    permissionModule: "settings",
    label: "Document Numbering",
    description: "Prefixes, padding & sequence resets",
    icon: FileText,
    route: "/settings/document-numbering",
    accent: "gold",
    group: "system",
  },
  // Permissions & Roles moved to the Security module (/security/roles)
  // — the old /settings/permissions route redirects there.
  {
    key: "storefront",
    permissionModule: "settings",
    label: "Storefront",
    description: "Homepage content, formats & scents",
    icon: Sparkles,
    route: "/settings/storefront",
    accent: "rose",
    group: "system",
    // Orika Living (diffusers) is the only business with a storefront.
    businesses: ["diffusers"],
  },
  {
    key: "help-editor",
    permissionModule: "help",
    label: "Help Center Editor",
    description: "Manage guides and FAQs",
    icon: HelpCircle,
    route: "/settings/help-editor",
    accent: "gold",
    group: "system",
  },
];
