// ── lib/constants/salesCampaignConstants.ts ───────────────────────────────────
import { z } from "zod";

export const CAMPAIGN_TEMPLATE_META = {
  minimal: {
    label: "Minimal",
    desc: "Clean and elegant — products take centre stage",
  },
  editorial: {
    label: "Editorial",
    desc: "Full-bleed hero image with luxury editorial feel",
  },
  bold: { label: "Bold", desc: "High contrast + countdown — maximum urgency" },
} as const;

// Which landing-page sections show by default. Used as a fallback whenever a
// campaign's `sections` is empty/missing (older campaigns were created before
// sections were seeded), so the public page and the builder toggles always
// have something to render. Mirrors the DB default on sales_campaigns.sections.
export const DEFAULT_CAMPAIGN_SECTIONS: Record<string, boolean> = {
  hero: true,
  countdown: true,
  products: true,
  inquiry_form: true,
  whatsapp_button: true,
  stock_indicator: true,
};

// Brand-aligned accent colours, selectable per campaign. Gold (#C9A86C) is the
// house colour and the default; the rest are tasteful, on-brand alternatives.
export const DEFAULT_ACCENT = "#C9A86C";
export const CAMPAIGN_ACCENTS: { label: string; value: string }[] = [
  { label: "Gold", value: "#C9A86C" },
  { label: "Champagne", value: "#D9BC87" },
  { label: "Rose", value: "#C2728A" },
  { label: "Emerald", value: "#2D6A4F" },
  { label: "Royal", value: "#6C5CE7" },
  { label: "Sky", value: "#2D9CDB" },
];

export const ORDER_STATUS_META: Record<
  string,
  { label: string; color: string }
> = {
  pending: { label: "Awaiting proof", color: "#F97316" },
  proof_submitted: { label: "Verifying payment", color: "#C9A86C" },
  confirmed: { label: "Confirmed", color: "#2D9CDB" },
  dispatched: { label: "Dispatched", color: "#7B68EE" },
  ready_for_pickup: { label: "Ready for pickup", color: "#2D6A4F" },
  completed: { label: "Completed", color: "#2D6A4F" },
  cancelled: { label: "Cancelled", color: "#EF4444" },
};

export const NIGERIAN_STATES = [
  "Abia",
  "Abuja (FCT)",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

// ISO 3166-2 zone codes for Nigerian states (maps state name → delivery zone code)
export const NIGERIA_STATE_ZONE_CODES: Record<string, string> = {
  "Abia": "NG-AB",
  "Abuja (FCT)": "NG-FC",
  "Adamawa": "NG-AD",
  "Akwa Ibom": "NG-AK",
  "Anambra": "NG-AN",
  "Bauchi": "NG-BA",
  "Bayelsa": "NG-BY",
  "Benue": "NG-BE",
  "Borno": "NG-BO",
  "Cross River": "NG-CR",
  "Delta": "NG-DE",
  "Ebonyi": "NG-EB",
  "Edo": "NG-ED",
  "Ekiti": "NG-EK",
  "Enugu": "NG-EN",
  "Gombe": "NG-GO",
  "Imo": "NG-IM",
  "Jigawa": "NG-JI",
  "Kaduna": "NG-KD",
  "Kano": "NG-KN",
  "Katsina": "NG-KT",
  "Kebbi": "NG-KE",
  "Kogi": "NG-KO",
  "Kwara": "NG-KW",
  "Lagos": "NG-LA",
  "Nasarawa": "NG-NA",
  "Niger": "NG-NI",
  "Ogun": "NG-OG",
  "Ondo": "NG-ON",
  "Osun": "NG-OS",
  "Oyo": "NG-OY",
  "Plateau": "NG-PL",
  "Rivers": "NG-RI",
  "Sokoto": "NG-SO",
  "Taraba": "NG-TA",
  "Yobe": "NG-YO",
  "Zamfara": "NG-ZA",
};

// Lagos LGAs with their delivery zone codes
export const LAGOS_LGAS: Array<{ name: string; code: string }> = [
  { name: "Agege", code: "NG-LA-AGEGE" },
  { name: "Ajeromi-Ifelodun", code: "NG-LA-AJEROMI" },
  { name: "Alimosho", code: "NG-LA-ALIMOSHO" },
  { name: "Amuwo-Odofin", code: "NG-LA-AMUWO" },
  { name: "Apapa", code: "NG-LA-APAPA" },
  { name: "Badagry", code: "NG-LA-BADAGRY" },
  { name: "Epe", code: "NG-LA-EPE" },
  { name: "Eti-Osa (Lekki / VI / Ikoyi)", code: "NG-LA-ETI-OSA" },
  { name: "Ibeju-Lekki", code: "NG-LA-IBEJU" },
  { name: "Ifako-Ijaiye", code: "NG-LA-IFAKO" },
  { name: "Ikeja", code: "NG-LA-IKEJA" },
  { name: "Ikorodu", code: "NG-LA-IKORODU" },
  { name: "Kosofe", code: "NG-LA-KOSOFE" },
  { name: "Lagos Island", code: "NG-LA-ISLAND" },
  { name: "Lagos Mainland (Yaba / Ebute-Metta)", code: "NG-LA-MAINLAND" },
  { name: "Mushin", code: "NG-LA-MUSHIN" },
  { name: "Ojo", code: "NG-LA-OJO" },
  { name: "Oshodi-Isolo", code: "NG-LA-OSHODI" },
  { name: "Shomolu", code: "NG-LA-SHOMOLU" },
  { name: "Surulere", code: "NG-LA-SURULERE" },
];

// World countries sorted alphabetically — Nigeria first for prominence.
export const WORLD_COUNTRIES: Array<{ name: string; code: string }> = [
  { name: "Nigeria", code: "NG" },
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Brazil", code: "BR" },
  { name: "Brunei", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cabo Verde", code: "CV" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cote d'Ivoire", code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czechia", code: "CZ" },
  { name: "Democratic Republic of the Congo", code: "CD" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Eswatini", code: "SZ" },
  { name: "Ethiopia", code: "ET" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR" },
  { name: "Grenada", code: "GD" },
  { name: "Guatemala", code: "GT" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Holy See (Vatican City)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia", code: "FM" },
  { name: "Moldova", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "North Korea", code: "KP" },
  { name: "North Macedonia", code: "MK" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestine", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Qatar", code: "QA" },
  { name: "Republic of the Congo", code: "CG" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Korea", code: "KR" },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syria", code: "SY" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

// Zod schemas
export const campaignSchema = z.object({
  campaign_name: z.string().min(2, "Campaign name required"),
  slug: z
    .string()
    .min(2)
    .regex(/^[a-z0-9-]+$/, "Only lowercase letters, numbers, hyphens"),
  campaign_type: z.enum(["online", "popup_event"]).default("online"),
  template: z.enum(["minimal", "editorial", "bold"]).default("editorial"),
  headline: z.string().optional().or(z.literal("")),
  subheadline: z.string().optional().or(z.literal("")),
  body_copy: z.string().optional().or(z.literal("")),
  hero_image_url: z.string().optional().or(z.literal("")),
  accent_color: z.string().optional().or(z.literal("")),
  discount_type: z.enum(["percentage", "fixed_amount", "none"]).default("none"),
  discount_value: z.number().min(0).optional(),
  start_date: z.string().optional().or(z.literal("")),
  end_date: z.string().optional().or(z.literal("")),
  is_evergreen: z.boolean().default(false),
  whatsapp_number: z.string().optional().or(z.literal("")),
  store_location: z.string().optional().or(z.literal("")),
  redirect_url: z.string().url().optional().or(z.literal("")),
});
export type CampaignFormValues = z.infer<typeof campaignSchema>;

export const checkoutSchema = z.object({
  customer_name: z.string().min(2, "Name required"),
  customer_phone: z.string().min(10, "Valid phone required"),
  customer_email: z.string().email().optional().or(z.literal("")),
  fulfilment_type: z.enum(["delivery", "pickup"]),
  delivery_address: z
    .object({
      country: z.string().min(1, "Country required"),
      country_code: z.string().optional().or(z.literal("")),
      zone_code: z.string().optional().or(z.literal("")),
      line1: z.string().min(5, "Address required"),
      city: z.string().min(1, "City / LGA required"),
      state: z.string().optional().or(z.literal("")),
      landmark: z.string().optional().or(z.literal("")),
    })
    .superRefine((addr, ctx) => {
      if (addr.country === "Nigeria") {
        if (!addr.state || addr.state.length < 2) {
          ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: "Please select your state",
            path: ["state"],
          });
        }
      }
    })
    .optional(),
  payment_method: z.enum(["paystack", "bank_transfer", "optimus_pay"]),
  bank_account_id: z.string().uuid().optional(),
});
export type CheckoutFormValues = z.infer<typeof checkoutSchema>;
