import type { Metadata, Viewport } from "next";
import {
  Playfair_Display,
  Montserrat,
  JetBrains_Mono,
  Italiana,
  Fraunces,
  Inter_Tight,
} from "next/font/google";
import { headers } from "next/headers";
import { getBrand } from "@/lib/brand";
import "@/styles/globals.css";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});
const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
  weight: ["400", "500", "700"],
});
// Reserved for the intro overlay headline only — deliberately distinct from
// the site's regular display/body faces so the welcome reads as cinematic.
const italiana = Italiana({
  subsets: ["latin"],
  variable: "--font-cinematic",
  display: "swap",
  weight: "400",
});
// Atelier sales-landing faces (packages/landing-kit). Self-hosted via next/font
// so the live page matches the Lovable reference (Fraunces display + Inter
// Tight body) with the real variable axes (opsz/SOFT) the design relies on.
const fraunces = Fraunces({
  subsets: ["latin"],
  style: ["normal", "italic"],
  axes: ["opsz", "SOFT", "WONK"],
  variable: "--font-atelier-display",
  display: "swap",
});
const interTight = Inter_Tight({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-atelier-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sales",
  description: "A time-bound sale, designed end-to-end.",
  formatDetection: { telephone: false, email: false, address: false },
  manifest: "/manifest.webmanifest",
  // Static defaults generated by scripts/generate-favicon.mjs into
  // apps/landing/public. The apex page's generateMetadata overrides these with
  // the brand's configured favicon when one is set in the Landing Studio.
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
};

export const viewport: Viewport = {
  themeColor: "#0F0809",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const brand = getBrand();

  return (
    <html
      lang="en"
      data-business={brand}
      className={`${playfair.variable} ${montserrat.variable} ${jetbrains.variable} ${italiana.variable} ${fraunces.variable} ${interTight.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
