import type { Metadata, Viewport } from "next";
import {
  Playfair_Display,
  Montserrat,
  JetBrains_Mono,
  Italiana,
  Fraunces,
  Inter_Tight,
} from "next/font/google";
import { headers } from "next/headers";
import { getBrand } from "@/lib/brand";
import { fetchPublishedLanding } from "@/lib/api";
import { withDefaults, type LandingConfig } from "@landing-kit";
import { PwaCleanup } from "@/components/PwaCleanup";
import { MetaPixel } from "@/components/MetaPixel";
import { CookieConsentBanner } from "@/components/CookieConsentBanner";
import { CartGlitchModal } from "@/components/cart/CartGlitchModal";
import { EU_EEA_UK } from "@/lib/eu-countries";
import "@/styles/globals.css";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});
const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
  weight: ["400", "500", "700"],
});
// Reserved for the intro overlay headline only — deliberately distinct from
// the site's regular display/body faces so the welcome reads as cinematic.
const italiana = Italiana({
  subsets: ["latin"],
  variable: "--font-cinematic",
  display: "swap",
  weight: "400",
});
// Atelier sales-landing faces (packages/landing-kit). Self-hosted via next/font
// so the live page matches the Lovable reference (Fraunces display + Inter
// Tight body) with the real variable axes (opsz/SOFT) the design relies on.
const fraunces = Fraunces({
  subsets: ["latin"],
  style: ["normal", "italic"],
  axes: ["opsz", "SOFT", "WONK"],
  variable: "--font-atelier-display",
  display: "swap",
});
const interTight = Inter_Tight({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-atelier-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sales",
  description: "A time-bound sale, designed end-to-end.",
  formatDetection: { telephone: false, email: false, address: false },
  manifest: "/manifest.webmanifest",
  // Static defaults generated by scripts/generate-favicon.mjs into
  // apps/landing/public. The apex page's generateMetadata overrides these with
  // the brand's configured favicon when one is set in the Landing Studio.
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
};

export const viewport: Viewport = {
  themeColor: "#0F0809",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const brand = getBrand();

  // Resolve the brand's Meta Pixel id from its published landing config, with
  // the brand defaults filled in (so Faitlyn's seeded pixel fires even before
  // a config is published). Falls back to a build-time env var for local dev.
  // Sanitised to digits so it is safe to inline into the pixel init. A failed
  // fetch must never break the page — degrade to "no pixel".
  const rawLanding = await fetchPublishedLanding(brand).catch(() => null);
  const landing = withDefaults(
    brand,
    rawLanding as Partial<LandingConfig> | null,
  );
  const pixelId = (
    landing.seo.metaPixelId ||
    process.env.NEXT_PUBLIC_FB_PIXEL_ID ||
    ""
  ).replace(/[^0-9]/g, "");

  const country = (headers().get("x-visitor-country") || "").toUpperCase();
  const isEu = EU_EEA_UK.has(country);

  return (
    <html
      lang="en"
      data-business={brand}
      className={`${playfair.variable} ${montserrat.variable} ${jetbrains.variable} ${italiana.variable} ${fraunces.variable} ${interTight.variable}`}
    >
      <body>
        {pixelId ? <MetaPixel pixelId={pixelId} isEu={isEu} /> : null}
        {pixelId ? <CookieConsentBanner isEu={isEu} /> : null}
        <PwaCleanup />
        {/* One-time apology + free-gift modal. Self-gating: only shows for buyers
            whose broken cart was cleared by the checkout-glitch migration. */}
        <CartGlitchModal />
        {children}
      </body>
    </html>
  );
}
