import { QueryClient } from "@tanstack/react-query";
import { createRouter as createTanStackRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";
/**
 * Router factory. `routeTree.gen.ts` is generated by the TanStack Start vite
 * plugin on the first `vite dev` / `vite build` — it is gitignored. Until you
 * run dev once, your editor will flag the import as missing; that's expected.
 */
export const createRouter = () => {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        staleTime: 30_000,
        retry: 1,
      },
    },
  });

  return createTanStackRouter({
    routeTree,
    context: { queryClient },
    scrollRestoration: true,
    defaultPreloadStaleTime: 0,
  });
};