/**
 * AI Insights (V2.2 §6.30) — business logic.
 *
 * Tier-1 proactive insights: detectors read the live spine and raise
 * idempotent flag records the CEO can list / acknowledge / resolve. The
 * detectors ARE the system connection — overdue invoices (Invoicing), stale
 * intercompany (Intercompany), approval backlog (Org/Workflow), and the
 * anti-pocketing service-match (Service Jobs ↔ Sales). Stock/margin/attendance
 * categories are fed through `raise()` by their own modules or future
 * detectors. Tier-2 AI narration (briefings) is generated by the AI layer
 * (Dashboards) — out of scope here.
 */

"use strict";

const repo = require("./insights.repo");
const events = require("./insights.events");
const { audit } = require("../../middleware/audit");
const { money } = require("../../utils/money");
const { logger } = require("../../config/logger");
const { listBrands } = require("../../config/brands");
const { NotFoundError, AppError } = require("../../utils/errors");

const VALID_CATEGORIES = Object.keys(repo.TABLE);

function assertCategory(category) {
  if (!VALID_CATEGORIES.includes(category))
    throw new AppError(
      "BAD_CATEGORY",
      `Unknown insight category ${category}`,
      422,
    );
}

// ── Read / lifecycle (CEO dashboard surface) ───────────────
function list({ brand, category, status, severity, page, page_size }) {
  assertCategory(category);
  return repo.list({
    category,
    business: brand,
    status,
    severity,
    page,
    page_size,
  });
}
function summary({ brand }) {
  return repo.openCounts({ business: brand });
}
async function getOne({ category, id }) {
  assertCategory(category);
  const row = await repo.getOne({ category, id });
  if (!row) throw new NotFoundError("Insight");
  return row;
}
async function acknowledge({ brand, user, request_id, category, id }) {
  assertCategory(category);
  const row = await repo.setStatus({
    category,
    id,
    status: "acknowledged",
    fields: {
      acknowledged_by: user.user_id,
      acknowledged_at: new Date().toISOString(),
    },
  });
  if (!row) throw new NotFoundError("Insight");
  await audit({
    business: brand,
    user_id: user.user_id,
    action_key: "ai_insights.acknowledge",
    target_type: category,
    target_id: id,
    request_id,
  });
  return row;
}
async function resolve({ brand, user, request_id, category, id, reason }) {
  assertCategory(category);
  const fields = { resolved_at: new Date().toISOString() };
  // service_match uses resolution_notes/resolved_by; others use resolved_reason
  if (category === "service_match") {
    fields.resolved_by = user.user_id;
    fields.resolution_notes = reason || null;
  } else {
    fields.resolved_reason = reason || null;
  }
  const row = await repo.setStatus({
    category,
    id,
    status: "resolved",
    fields,
  });
  if (!row) throw new NotFoundError("Insight");
  await audit({
    business: brand,
    user_id: user.user_id,
    action_key: "ai_insights.resolve",
    target_type: category,
    target_id: id,
    request_id,
  });
  return row;
}
async function dismiss({ brand, user, request_id, category, id }) {
  assertCategory(category);
  const row = await repo.setStatus({
    category,
    id,
    status: "dismissed",
    fields: {},
  });
  if (!row) throw new NotFoundError("Insight");
  await audit({
    business: brand,
    user_id: user.user_id,
    action_key: "ai_insights.dismiss",
    target_type: category,
    target_id: id,
    request_id,
  });
  return row;
}

/** Generic ingest hook for other modules / detectors. */
async function raise({ category, row }) {
  switch (category) {
    case "stock":
      return repo.raiseStock({ r: row });
    case "margin":
      return repo.raiseMargin({ r: row });
    case "invoice":
      return repo.raiseInvoice({ r: row });
    case "intercompany":
      return repo.raiseIntercompany({ r: row });
    case "attendance":
      return repo.raiseAttendance({ r: row });
    case "approval":
      return repo.raiseApproval({ r: row });
    case "service_match":
      return repo.raiseServiceMatch({ r: row });
    default:
      throw new AppError(
        "BAD_CATEGORY",
        `Unknown insight category ${category}`,
        422,
      );
  }
}

// ── Detectors ──────────────────────────────────────────────
function overdueSeverity(days) {
  if (days >= 90) return "critical";
  if (days >= 60) return "high";
  if (days >= 30) return "medium";
  return "low";
}
async function detectInvoices({ brand }) {
  const rows = await repo.overdueInvoices({ brand });
  let raised = 0;
  for (const inv of rows) {
    const days = Number(inv.days_overdue) || 0;
    await repo.raiseInvoice({
      r: {
        business: brand,
        alert_type: days >= 60 ? "overdue_long" : "overdue",
        invoice_id: inv.invoice_id,
        customer_contact_id: inv.customer_contact_id,
        amount_ngn: inv.net_due_ngn,
        days_overdue: days,
        severity: overdueSeverity(days),
        suppression_key: `overdue:${inv.invoice_id}`,
      },
    });
    raised += 1;
  }
  return raised;
}
async function detectIntercompany() {
  const rows = await repo.staleIntercompany({ within_days: 7 });
  let raised = 0;
  for (const ic of rows) {
    const age = Number(ic.age_days) || 0;
    const severity = age >= 30 ? "critical" : age >= 14 ? "high" : "medium";
    await repo.raiseIntercompany({
      r: {
        ic_transaction_id: ic.ic_transaction_id,
        alert_type: "pending_too_long",
        seller_brand: ic.seller_brand,
        buyer_brand: ic.buyer_brand,
        amount_ngn: ic.amount_ngn,
        age_days: age,
        severity,
        suppression_key: `stale:${ic.ic_transaction_id}`,
      },
    });
    raised += 1;
  }
  return raised;
}
async function detectApprovals() {
  const rows = await repo.staleApprovals({ within_hours: 48 });
  let raised = 0;
  for (const q of rows) {
    const hours = Number(q.oldest_age_hours) || 0;
    const severity =
      hours >= 168 ? "critical" : hours >= 96 ? "high" : "medium";
    await repo.raiseApproval({
      r: {
        business: q.business,
        alert_type: "queue_growing",
        pending_count: q.pending_count,
        oldest_age_hours: hours,
        severity,
        suppression_key: `queue:${q.business}`,
      },
    });
    raised += 1;
  }
  return raised;
}
async function detectServiceMatch({ brand }) {
  const rows = await repo.unlinkedServiceJobs({ brand });
  let raised = 0;
  for (const job of rows) {
    const expected = money(job.actual_cost_ngn || job.agreed_cost_ngn || 0);
    await repo.raiseServiceMatch({
      r: {
        business: brand,
        service_job_id: job.job_id,
        service_job_number: job.job_number,
        completed_by_stylist_id: job.assigned_stylist_id,
        completed_by_user_id: job.assigned_staff_user_id,
        alert_type: "no_sale_linked",
        job_completed_at: job.completed_at || new Date().toISOString(),
        expected_amount_ngn: expected.gt(0) ? expected.toFixed(2) : null,
        found_amount_ngn: "0.00",
        variance_ngn: expected.gt(0) ? expected.toFixed(2) : null,
        severity: expected.gte(money("50000")) ? "high" : "medium",
        suppression_key: `no_sale:${job.job_id}`,
      },
    });
    raised += 1;
  }
  return raised;
}

/** Full detector sweep (cron). Per-brand + shared detectors, best-effort. */
async function runDetectorSweep() {
  const result = { invoice: 0, intercompany: 0, approval: 0, service_match: 0 };
  for (const brand of listBrands()) {
    try {
      result.invoice += await detectInvoices({ brand });
    } catch (err) {
      logger.error(
        { err: err.message, brand },
        "insights: invoice detector failed",
      );
    }
    try {
      result.service_match += await detectServiceMatch({ brand });
    } catch (err) {
      logger.error(
        { err: err.message, brand },
        "insights: service-match detector failed",
      );
    }
  }
  try {
    result.intercompany = await detectIntercompany();
  } catch (err) {
    logger.error(
      { err: err.message },
      "insights: intercompany detector failed",
    );
  }
  try {
    result.approval = await detectApprovals();
  } catch (err) {
    logger.error({ err: err.message }, "insights: approval detector failed");
  }
  const total = Object.values(result).reduce((a, b) => a + b, 0);
  events.emit("sweep.completed", { ...result, total });
  logger.info(result, "ai insights detector sweep done");
  return result;
}

module.exports = {
  list,
  summary,
  getOne,
  acknowledge,
  resolve,
  dismiss,
  raise,
  runDetectorSweep,
  VALID_CATEGORIES,
};
